import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import "./work.css";

type Desk = { officeDeskId: string; deskCode: string; deskName: string; openCount: number; overdueCount: number; dueTodayCount: number; needsReviewCount: number; staleCount: number; noNamedHandlerCount: number };
type Item = { workItemId: string; title: string; priority: string; status: string; workstreamId?: string; workstreamName: string; currentDeskName: string; assignedUserDisplayName?: string; dueState: string; revision: number; canReassign: boolean; noNamedHandler: boolean; isStale: boolean; hasSubmittedContribution: boolean; hasActiveHelp: boolean };
type Pulse = { summary: Record<string, number>; deskWorkloads: Desk[]; items: Item[]; totalCount: number; page: number; pageSize: number };
type Option = { officeDeskId: string; name: string };
type Member = { userId: string; displayName: string };
const labels: Record<string, string> = { open: "Open", overdue: "Overdue", "due-today": "Due Today", "needs-review": "Needs Review", "waiting-on-help": "Waiting on Help", "not-started": "Not Started", "no-named-handler": "No Named Handler", stale: "Stale" };
const summaryKey: Record<string, string> = { "due-today": "dueToday", "needs-review": "needsReview", "waiting-on-help": "waitingOnHelp", "not-started": "notStarted", "no-named-handler": "noNamedHandler" };
const attentionOrder = ["overdue", "due-today", "needs-review", "waiting-on-help", "stale", "no-named-handler", "not-started", "open"];

export function BranchPulse() {
  const [data, setData] = useState<Pulse | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(true);
  const [attention, setAttention] = useState(""), [deskId, setDeskId] = useState(""), [workstreamId, setWorkstreamId] = useState(""), [q, setQ] = useState(""), [priority, setPriority] = useState(""), [staleDays, setStaleDays] = useState("7"), [page, setPage] = useState(0);
  const [routing, setRouting] = useState<{ id: string; revision: number; desks: Option[] } | null>(null), [members, setMembers] = useState<Member[]>([]), [targetDesk, setTargetDesk] = useState(""), [targetUser, setTargetUser] = useState(""), [reason, setReason] = useState(""), [membersLoading, setMembersLoading] = useState(false), [submitting, setSubmitting] = useState(false), [routeError, setRouteError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const p = new URLSearchParams({ page: String(page), pageSize: "25", staleDays }); if (attention) p.set("attention", attention); if (deskId) p.set("deskId", deskId); if (workstreamId) p.set("workstreamId", workstreamId); if (q.trim()) p.set("q", q.trim()); if (priority) p.set("priority", priority); const r = await fetch(`/api/work-items/branch-pulse?${p}`, { credentials: "include" }); if (!r.ok) throw new Error(await r.text() || "Branch Pulse could not be loaded."); setData(await r.json()); } catch (e) { setError(e instanceof Error ? e.message : "Branch Pulse could not be loaded."); } finally { setLoading(false); } }, [attention, deskId, workstreamId, q, priority, staleDays, page]);
  useEffect(() => { void load(); }, [load]);
  const reset = () => { setAttention(""); setDeskId(""); setWorkstreamId(""); setQ(""); setPriority(""); setStaleDays("7"); setPage(0); };
  const active = [["Search", q], ["Priority", priority], ["Attention", attention && labels[attention]], ["Desk", deskId && data?.deskWorkloads.find(d => d.officeDeskId === deskId)?.deskName], ["Workstream", workstreamId], ["Stale after", staleDays !== "7" && `${staleDays} days`]].filter(([, v]) => v);
  const chooseDesk = async (value: string) => { setTargetDesk(value); setTargetUser(""); setMembers([]); setRouteError(null); if (!routing || !value) return; setMembersLoading(true); try { const r = await fetch(`/api/work-items/${routing.id}/reassign-options?deskId=${encodeURIComponent(value)}`, { credentials: "include" }); if (!r.ok) throw new Error(await r.text() || "Members could not be loaded."); setMembers((await r.json()).members ?? []); } catch (e) { setRouteError(e instanceof Error ? e.message : "Members could not be loaded."); } finally { setMembersLoading(false); } };
  const openRouting = async (item: Item) => { setRouteError(null); try { const r = await fetch(`/api/work-items/${item.workItemId}/reassign-options`, { credentials: "include" }); if (!r.ok) throw new Error(await r.text() || "Reassignment options could not be loaded."); const x = await r.json(); setRouting({ id: item.workItemId, revision: item.revision, desks: x.desks ?? [] }); setTargetDesk(""); setTargetUser(""); setMembers([]); setReason(""); } catch (e) { setError(e instanceof Error ? e.message : "Reassignment options could not be loaded."); } };
  if (loading) return <main className="my-work-container"><p>Loading Branch Pulse…</p></main>;
  if (error) return <main className="my-work-container"><p role="alert">{error}</p><button onClick={() => void load()}>Retry</button></main>;
  const workstreams = (data as Pulse & { workstreams?: Array<{ workstreamId: string; workstreamName: string }> })?.workstreams ?? [];
  return <main className="my-work-container"><header className="my-work-header"><div><h1>Branch Pulse</h1><p className="my-work-subtitle">Authorized operational-area health.</p></div></header>
    <section className="my-work-filter-bar"><input aria-label="Search work" value={q} onChange={e => { setPage(0); setQ(e.target.value); }} placeholder="Search work" /><select aria-label="Workstream" value={workstreamId} onChange={e => { setPage(0); setWorkstreamId(e.target.value); }}><option value="">All workstreams</option>{workstreams.map(w => <option key={w.workstreamId} value={w.workstreamId}>{w.workstreamName}</option>)}</select><select aria-label="Priority" value={priority} onChange={e => { setPage(0); setPriority(e.target.value); }}><option value="">All priorities</option><option>Routine</option><option>Urgent</option><option>Immediate</option></select><label>Stale after <input type="number" min="1" max="90" value={staleDays} onChange={e => { setPage(0); setStaleDays(e.target.value); }} /> days</label><button onClick={reset}>Reset filters</button></section>
    {!!active.length && <p aria-live="polite">Active filters: {active.map(([k, v]) => `${k}: ${v}`).join(" · ")}</p>}
    <section className="my-work-summary-grid" aria-label="Attention summary">{attentionOrder.filter(k => data?.summary[summaryKey[k] ?? k] !== undefined).map(k => <button key={k} className="my-work-summary-card" aria-pressed={attention === k} onClick={() => { setPage(0); setAttention(attention === k ? "" : k); }}><span>{labels[k]}</span><strong>{data?.summary[summaryKey[k] ?? k]}</strong></button>)}</section>
    <section><h2>Desk workload</h2><div className="my-work-summary-grid">{data?.deskWorkloads.map(d => <button key={d.officeDeskId} className="my-work-summary-card" aria-pressed={deskId === d.officeDeskId} onClick={() => { setPage(0); setDeskId(deskId === d.officeDeskId ? "" : d.officeDeskId); }}><strong>{d.deskName}</strong><span>{d.openCount} open · {d.overdueCount} overdue · {d.dueTodayCount} due today · {d.needsReviewCount} review</span></button>)}</div></section>
    <section><h2>Attention list</h2>{data?.items.length ? data.items.map(i => <article className="my-work-item" key={i.workItemId}><div><h3>{i.title}</h3><p>{i.workstreamName} · {i.currentDeskName} · {i.assignedUserDisplayName ?? "No Named Handler"}</p><p>{[i.dueState === "overdue" && "Overdue", i.dueState === "today" && "Due Today", i.hasSubmittedContribution && "Needs Review", i.hasActiveHelp && "Waiting on Help", i.isStale && "Stale", i.noNamedHandler && "No Named Handler"].filter(Boolean).join(" · ")}</p></div><div className="my-work-item-actions"><Link to={`/work/${i.workItemId}`}>Open Work</Link>{i.canReassign && <button onClick={() => void openRouting(i)}>Reassign Work</button>}</div></article>) : <div className="my-work-empty-state"><h3>No work matches this view</h3><p>There are no authorized work items in this attention bucket.</p></div>}<div><button disabled={page === 0} onClick={() => setPage(page - 1)}>Previous</button><span> Page {page + 1} · {data?.totalCount ?? 0} results </span><button disabled={!data || (page + 1) * data.pageSize >= data.totalCount} onClick={() => setPage(page + 1)}>Next</button></div></section>
    {routing && <div role="dialog" aria-modal="true" className="modal-overlay"><form className="modal-content" onSubmit={async e => { e.preventDefault(); if (submitting) return; setSubmitting(true); setRouteError(null); try { const r = await fetch(`/api/work-items/${routing.id}/reassign`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ officeDeskId: targetDesk, assignedUserId: targetUser || null, reason, expectedRevision: routing.revision }) }); if (!r.ok) throw new Error(await r.text() || "Reassignment could not be completed."); setRouting(null); await load(); } catch (x) { setRouteError(x instanceof Error ? x.message : "Reassignment could not be completed."); } finally { setSubmitting(false); } }}><h2>Reassign Work</h2>{routeError && <p role="alert">{routeError}</p>}<label>Responsible desk<select required disabled={submitting} value={targetDesk} onChange={e => void chooseDesk(e.target.value)}><option value="">Select desk</option>{routing.desks.map(d => <option key={d.officeDeskId} value={d.officeDeskId}>{d.name}</option>)}</select></label><label>Named handler (optional)<select disabled={!targetDesk || membersLoading || submitting} value={targetUser} onChange={e => setTargetUser(e.target.value)}><option value="">{membersLoading ? "Loading members…" : "No Named Handler"}</option>{members.map(m => <option key={m.userId} value={m.userId}>{m.displayName}</option>)}</select></label><label>Reason<textarea required disabled={submitting} value={reason} onChange={e => setReason(e.target.value)} /></label><button type="button" disabled={submitting} onClick={() => setRouting(null)}>Cancel</button><button type="submit" disabled={submitting || membersLoading}>{submitting ? "Reassigning…" : "Reassign"}</button></form></div>}
  </main>;
}
