using LAC.Domain;
using LAC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;
namespace LAC.Tests;
public sealed class KhasraTests {
 [Theory][InlineData(" 22//2 ","22//2")][InlineData("22 // 1/6","22//1/6")][InlineData("22//2 min","22//2MIN")]
 public void Normalizes_without_destroying_historical_display_text(string input,string expected)=>Assert.Equal(expected,KhasraNumber.Normalize(input));
 [Fact] public async Task Same_normalized_number_cannot_exist_in_one_village(){await using var db=Db();var v=new Village{Name="A"};db.Add(v);db.Add(new Khasra{Village=v,DisplayNumber="22//2",NormalizedNumber="22//2"});await db.SaveChangesAsync();db.Add(new Khasra{Village=v,DisplayNumber="22 // 2",NormalizedNumber="22//2"});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());}
 [Fact] public async Task Same_number_can_exist_in_different_villages(){await using var db=Db();var a=new Village{Name="A"};var b=new Village{Name="B"};db.AddRange(a,b,new Khasra{Village=a,DisplayNumber="22//2",NormalizedNumber="22//2"},new Khasra{Village=b,DisplayNumber="22//2",NormalizedNumber="22//2"});await db.SaveChangesAsync();Assert.Equal(2,await db.Khasras.CountAsync());}
 [Fact] public async Task Award_and_notification_are_distinct_khasra_relationships(){await using var db=Db();var v=new Village{Name="A"};var k=new Khasra{Village=v,DisplayNumber="22//2",NormalizedNumber="22//2"};var a=new Award{AwardNumber="D-1"};var n=new Notification{AcquisitionProject=new AcquisitionProject{Name="P"},SectionType="3A",NotificationNumber="N-1"};db.AddRange(k,a,n,new AwardKhasra{Award=a,Khasra=k,AcquiredArea=2m},new NotificationKhasra{Notification=n,Khasra=k,NotifiedArea=3m});await db.SaveChangesAsync();Assert.Equal(2m,(await db.Set<AwardKhasra>().SingleAsync()).AcquiredArea);Assert.Equal(3m,(await db.Set<NotificationKhasra>().SingleAsync()).NotifiedArea);}
 [Fact] public void Lr_row_requires_raw_khasra_text(){var row=new LREntry{RawKhasraText="22//2 min",VerificationStatus=VerificationStatus.NeedsReview};Assert.False(string.IsNullOrWhiteSpace(row.RawKhasraText));Assert.Equal(VerificationStatus.NeedsReview,row.VerificationStatus);}
 [Fact] public async Task One_document_can_link_to_multiple_typed_entities_without_duplication(){await using var db=Db();var village=new Village{Name="A"};var khasra=new Khasra{Village=village,DisplayNumber="22//2",NormalizedNumber="22//2"};var document=new Document{OriginalFileName="demo.pdf",StoragePath="demo.pdf"};db.AddRange(village,khasra,document,new DocumentVillage{Document=document,Village=village},new DocumentKhasra{Document=document,Khasra=khasra});await db.SaveChangesAsync();Assert.Equal(1,await db.Documents.CountAsync());Assert.Equal(2,await db.DocumentVillages.CountAsync()+await db.DocumentKhasras.CountAsync());Assert.All(new[]{typeof(DocumentVillage),typeof(DocumentKhasra),typeof(DocumentAward),typeof(DocumentNotification),typeof(DocumentVillageLR)},type=>Assert.Contains(db.Model.FindEntityType(type)!.GetIndexes(),index=>index.IsUnique&&index.Properties.Count==2));}
 static LacDbContext Db(){var o=new DbContextOptionsBuilder<LacDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;return new LacDbContext(o);}
}
