using LAC.Domain;
using LAC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using Xunit;

namespace LAC.Tests;

public sealed class NmWorkflowTests
{
 [Fact] public async Task Exact_ocr_khasra_remains_unresolved_until_human_selects_it()
 { await using var db=Db(); var v=new Village{Name="Fictional"};var a=new Award{AwardNumber="A"};var d=new Document{DocumentType="NM",OriginalFileName="x.pdf",StoragePath="x"};var k=new Khasra{Village=v,DisplayNumber="1//2 min",NormalizedNumber="1//2",Qualifier="min"};db.AddRange(v,a,d,k,new AwardVillage{Award=a,Village=v});await db.SaveChangesAsync();var s=new NmWorkflowService(db);var nm=await s.CreateReviewAsync(d.Id,v.Id,a.Id,null,null,default);var row=await s.AddReviewRowAsync(nm.Id,new(1,"1","{}","Recorded Name",null,null,null,100m,null,[new("1//2 min","min")]),default);Assert.Null(row.Khasras.Single().SuggestedKhasraId);Assert.Equal(NmReviewStatus.NeedsReview,row.Khasras.Single().Status);await s.SelectKhasrasAsync(row.Id,"reviewer",[new(row.Khasras.Single().Id,k.Id)],default);Assert.Equal(k.Id,row.Khasras.Single().SuggestedKhasraId);Assert.Empty(await db.NmEntitlements.ToListAsync());Assert.Empty(await db.NmRecordedPeople.ToListAsync()); }
 [Fact] public async Task No_match_and_qualifier_mismatch_remain_needs_review()
 { await using var db=Db();var v=new Village{Name="F"};var d=new Document{OriginalFileName="x",StoragePath="x"};var k=new Khasra{Village=v,DisplayNumber="1//2 min",NormalizedNumber="1//2",Qualifier="min"};db.AddRange(v,d,k);await db.SaveChangesAsync();var s=new NmWorkflowService(db);var nm=await s.CreateReviewAsync(d.Id,v.Id,null,null,null,default);var r=await s.AddReviewRowAsync(nm.Id,new(1,"1","{}","N",null,null,null,null,null,[new("1//2",null),new("9//9",null)]),default);Assert.All(r.Khasras,x=>Assert.Equal(NmReviewStatus.NeedsReview,x.Status)); }
 [Fact] public async Task Commit_preserves_person_and_multiple_human_selected_khasras_without_party_or_payment()
 { await using var db=Db();var v=new Village{Name="F"};var d=new Document{OriginalFileName="x",StoragePath="x"};var ks=new[]{new Khasra{Village=v,DisplayNumber="1//1",NormalizedNumber="1//1"},new Khasra{Village=v,DisplayNumber="1//2",NormalizedNumber="1//2"}};db.AddRange(v,d);db.AddRange(ks);await db.SaveChangesAsync();var s=new NmWorkflowService(db);var nm=await s.CreateReviewAsync(d.Id,v.Id,null,null,null,default);var input=new NmRowInput(1,"1","{}","Same Name",null,"1/2",null,250m,"NM",[new("1//1",null),new("1//2",null)]);var row=await s.AddReviewRowAsync(nm.Id,input,default);await s.SelectKhasrasAsync(row.Id,"reviewer",row.Khasras.Zip(ks,(link,k)=>new NmKhasraSelection(link.Id,k.Id)).ToList(),default);await s.VerifyRowAsync(row.Id,"reviewer",input,default);await s.CommitAsync(nm.Id,"reviewer",default);var e=await db.NmEntitlements.Include(x=>x.NmRecordedPerson).Include(x=>x.KhasraLinks).SingleAsync();Assert.Equal(2,e.KhasraLinks.Count);Assert.Null(e.NmRecordedPerson.PartyId);Assert.Equal(250m,e.EntitlementAmount);Assert.Empty(await db.Set<AwardKhasra>().ToListAsync());Assert.Equal(4,await db.SourceEvidence.CountAsync()); }
 [Fact] public async Task Semantic_analysis_persists_field_provenance_ditto_relation_and_no_canonical_facts()
 { await using var db=Db();var v=new Village{Name="F"};var d=new Document{DocumentType="NM",OriginalFileName="x.pdf",StoragePath="x"};var k=new Khasra{Village=v,DisplayNumber="1//2",NormalizedNumber="1//2"};db.AddRange(v,d,k);await db.SaveChangesAsync();var nm=await new NmWorkflowService(db).CreateReviewAsync(d.Id,v.Id,null,null,null,default);var worker=new FakeIntelligence(d.Id,Payload());var service=new NmWorkflowService(db,new MemoryStorage(),worker);var session=await service.AnalyzeSemanticAsync(nm.Id,default);Assert.Equal(NmSemanticSessionStatus.Completed,session.Status);Assert.Equal(3,await db.NmSemanticOwnerBlocks.CountAsync());var inherited=await db.NmSemanticParcelEntries.SingleAsync(x=>x.IsInherited);Assert.Equal("1//2",inherited.RawKhasraText);Assert.False(string.IsNullOrWhiteSpace(inherited.KhasraSourceRegionJson));Assert.False(string.IsNullOrWhiteSpace(inherited.AreaSourceRegionJson));var relation=await db.NmSemanticSourceRelations.SingleAsync();Assert.Equal("ParcelInheritedFromPreviousOwnerBlock",relation.RelationType);Assert.Equal("-do-",relation.RawSourceText);Assert.False(string.IsNullOrWhiteSpace(relation.OriginalSourceRegionJson));Assert.Contains(await db.NmSemanticExceptions.Select(x=>x.Reason).ToListAsync(),x=>x=="PageContinuationAmbiguous");Assert.Empty(await db.NmRecordedPeople.ToListAsync());Assert.Empty(await db.NmEntitlements.ToListAsync());Assert.Empty(await db.NmEntitlementKhasras.ToListAsync());Assert.Empty(await db.NmEntitlementComponents.ToListAsync());Assert.Empty(await db.SourceEvidence.ToListAsync()); }
 private static JsonElement Payload()=>JsonDocument.Parse("""{"sourceSequence":1,"recordedNameRaw":"Owner A","shareRaw":"1/3","fieldSources":{"recordedName":{"page":1,"rawSourceText":"Owner A S/o X","sourceRegion":{"x":1}},"share":{"page":1,"rawSourceText":"1/3","sourceRegion":{"x":2}}},"status":"AutoStructured","parcels":[{"rawKhasraText":"1//2","rawAreaText":"0-14","isInherited":false,"khasraSource":{"page":1,"rawSourceText":"1//2","sourceRegion":{"x":3}},"areaSource":{"page":1,"rawSourceText":"0-14","sourceRegion":{"x":4}}}],"components":{"grand_total":{"rawAmountText":"100","source":{"page":1,"rawSourceText":"100","sourceRegion":{"x":5}}}},"relations":[],"exceptions":[]}""").RootElement.Clone();
 private sealed class FakeIntelligence(Guid documentId,JsonElement first):ILocalDocumentIntelligenceClient { public Task<LocalDocumentIntelligenceResult> RunAsync(LocalDocumentIntelligenceInput input,CancellationToken ct){var second=JsonDocument.Parse("""{"sourceSequence":2,"recordedNameRaw":"Owner B","shareRaw":"1/6","fieldSources":{"recordedName":{"page":1,"rawSourceText":"Owner B S/o Y","sourceRegion":{"x":6}},"share":{"page":1,"rawSourceText":"1/6","sourceRegion":{"x":7}}},"status":"AutoStructured","parcels":[{"rawKhasraText":"1//2","rawAreaText":"0-14","isInherited":true,"khasraSource":{"page":1,"rawSourceText":"1//2","sourceRegion":{"x":3}},"areaSource":{"page":1,"rawSourceText":"0-14","sourceRegion":{"x":4}}}],"components":{},"relations":[{"relationType":"ParcelInheritedFromPreviousOwnerBlock","relatedSourceSequence":1,"marker":{"page":1,"rawSourceText":"-do-","sourceRegion":{"x":8}}}],"exceptions":[]}""").RootElement.Clone();var continuation=JsonDocument.Parse("""{"reason":"PageContinuationAmbiguous","detail":"No explicit continuation evidence."}""").RootElement.Clone();return Task.FromResult(new LocalDocumentIntelligenceResult(1,documentId,"Completed",1,[new("NmSemanticOwnerBlock",first,1,null,null,null,null,null,null,null),new("NmSemanticOwnerBlock",second,1,null,null,null,null,null,null,null),new("NmSemanticException",continuation,2,null,null,null,null,null,null,null)],[],JsonDocument.Parse("{}").RootElement.Clone()));} }
 private sealed class MemoryStorage:IDocumentStorage { public Task<string> SaveAsync(Stream s,string n,CancellationToken c)=>Task.FromResult("x");public Task<DocumentStorageWriteResult> SaveAndHashAsync(Stream s,string n,CancellationToken c)=>Task.FromResult(new DocumentStorageWriteResult("x","x",1));public Task DeleteAsync(string p,CancellationToken c)=>Task.CompletedTask;public Task<Stream?> OpenReadAsync(string p,CancellationToken c)=>Task.FromResult<Stream?>(new MemoryStream([1]));public StorageHealth GetHealth()=>new("memory",true,null,null); }
 private static LacDbContext Db()=>new(new DbContextOptionsBuilder<LacDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
}
