using LAC.Domain;
using LAC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace LAC.Tests;
public class OwnershipServiceTests
{
 private static LacDbContext Db() => new(new DbContextOptionsBuilder<LacDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options);
 private static async Task<(LacDbContext Db, Village Village, Khasra Khasra, KhatauniRecord Record, Khata Khata)> SetupAsync()
 {
  var db=Db(); var district=new District{Name="Demo District"}; var subdivision=new SubDivision{District=district,Name="Demo Sub"}; var village=new Village{SubDivision=subdivision,Name="Demo Village"}; var khasra=new Khasra{Village=village,DisplayNumber="22//2",NormalizedNumber="22//2"}; var record=new KhatauniRecord{Village=village,ReferenceNumber="R-2024",AsOfDate=new DateOnly(2024,1,1),VerificationStatus=RevenueRecordVerificationStatus.Verified}; var khata=new Khata{KhatauniRecord=record,KhataNumber="145"}; db.AddRange(district,subdivision,village,khasra,record,khata); await db.SaveChangesAsync(); return(db,village,khasra,record,khata);
 }
 [Fact] public async Task Khata_links_multiple_khasras_and_parties_without_name_merge()
 { var (db,v,k,_,khata)=await SetupAsync(); var service=new OwnershipService(db); var k2=new Khasra{VillageId=v.Id,DisplayNumber="22//1/6",NormalizedNumber="22//1/6"}; db.Add(k2); await db.SaveChangesAsync(); await service.LinkKhasraAsync(khata.Id,k.Id,"22//2",null,null,null,null,default); await service.LinkKhasraAsync(khata.Id,k2.Id,"22//1/6",null,null,null,null,default); var first=await service.CreatePartyAsync(PartyType.Individual,"Demo Ram Singh",null,null,null,default); var second=await service.CreatePartyAsync(PartyType.Individual,"Demo Ram Singh",null,null,null,default); await service.AddShareAsync(khata.Id,first.Id,"1/2",1,2,null,RevenueRecordVerificationStatus.Verified,default); await service.AddShareAsync(khata.Id,second.Id,"1/2",1,2,null,RevenueRecordVerificationStatus.Verified,default); Assert.Equal(2,await db.KhataKhasras.CountAsync()); Assert.Equal(2,await db.Parties.CountAsync(x=>x.DisplayName=="Demo Ram Singh")); Assert.Equal(2,await db.KhataPartyShares.CountAsync()); }
 [Fact] public void Share_validation_reports_exact_complete_and_incomplete_states()
 { var full=OwnershipService.ValidateShares([new KhataPartyShare{ShareNumerator=1,ShareDenominator=2},new KhataPartyShare{ShareNumerator=1,ShareDenominator=2}]); var partial=OwnershipService.ValidateShares([new KhataPartyShare{ShareNumerator=1,ShareDenominator=2},new KhataPartyShare{ShareNumerator=1,ShareDenominator=4}]); var unknown=OwnershipService.ValidateShares([new KhataPartyShare{RawShareText="half"}]); Assert.True(full.IsValid); Assert.Contains("100%",full.Message); Assert.False(partial.IsValid); Assert.Contains("75%",partial.Message); Assert.False(unknown.IsComplete); Assert.Contains("incomplete",unknown.Message); }
 [Fact] public async Task Ownership_is_derived_historically_and_ambiguous_records_are_not_guessed()
 { var (db,v,k,oldRecord,oldKhata)=await SetupAsync(); var service=new OwnershipService(db); var party=await service.CreatePartyAsync(PartyType.Individual,"Demo Owner",null,null,null,default); await service.LinkKhasraAsync(oldKhata.Id,k.Id,"22//2",null,null,null,null,default); await service.AddShareAsync(oldKhata.Id,party.Id,"1/1",1,1,null,RevenueRecordVerificationStatus.Verified,default); var newer=new KhatauniRecord{VillageId=v.Id,ReferenceNumber="R-2025",AsOfDate=new DateOnly(2025,1,1),VerificationStatus=RevenueRecordVerificationStatus.Verified}; var newerKhata=new Khata{KhatauniRecord=newer,KhataNumber="146"}; db.AddRange(newer,newerKhata,new KhataKhasra{Khata=newerKhata,KhasraId=k.Id},new KhataPartyShare{Khata=newerKhata,PartyId=party.Id,ShareNumerator=1,ShareDenominator=1,VerificationStatus=RevenueRecordVerificationStatus.Verified}); await db.SaveChangesAsync(); var latest=await service.GetRecordedOwnershipAsync(k.Id,null,default); Assert.True(latest.Found); Assert.Equal(newer.Id,latest.KhatauniRecordId); var sameDate=new KhatauniRecord{VillageId=v.Id,ReferenceNumber="R-2025-B",AsOfDate=new DateOnly(2025,1,1),VerificationStatus=RevenueRecordVerificationStatus.Verified}; var sameKhata=new Khata{KhatauniRecord=sameDate,KhataNumber="147"}; db.AddRange(sameDate,sameKhata,new KhataKhasra{Khata=sameKhata,KhasraId=k.Id}); await db.SaveChangesAsync(); var ambiguous=await service.GetRecordedOwnershipAsync(k.Id,null,default); Assert.True(ambiguous.IsAmbiguous); }
 [Fact] public async Task Verified_khatauni_requires_complete_verified_shares()
 { var (db,_,k,record,khata)=await SetupAsync(); var service=new OwnershipService(db); var party=await service.CreatePartyAsync(PartyType.Individual,"Demo Owner",null,null,null,default); await service.LinkKhasraAsync(khata.Id,k.Id,"22//2",null,null,null,null,default); await service.AddShareAsync(khata.Id,party.Id,"half",null,null,null,RevenueRecordVerificationStatus.NeedsReview,default); record.VerificationStatus=RevenueRecordVerificationStatus.Draft; await db.SaveChangesAsync(); await Assert.ThrowsAsync<OwnershipWorkflowException>(()=>service.VerifyKhatauniAsync(record.Id,record.Version,default)); }
}
