// <auto-generated />
using System;
using LAC.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LAC.Infrastructure.Migrations
{
    [DbContext(typeof(LacDbContext))]
    [Migration("20260903072138_AddLrMigrationWorkflow")]
    partial class AddLrMigrationWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LAC.Domain.AcquisitionProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActRegime")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiringAgency")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AcquisitionProjects");
                });

            modelBuilder.Entity("LAC.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LAC.Domain.Award", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcquisitionProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActRegime")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AwardDate")
                        .HasColumnType("date");

                    b.Property<string>("AwardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AwardType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcquisitionProjectId");

                    b.HasIndex("AwardNumber")
                        .IsUnique();

                    b.ToTable("Awards");
                });

            modelBuilder.Entity("LAC.Domain.AwardKhasra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AcquiredArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("AcquisitionStatus")
                        .HasColumnType("text");

                    b.Property<string>("AreaUnit")
                        .HasColumnType("text");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KhasraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KhasraId");

                    b.HasIndex("AwardId", "KhasraId")
                        .IsUnique();

                    b.ToTable("AwardKhasra");
                });

            modelBuilder.Entity("LAC.Domain.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("LAC.Domain.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MimeType")
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("Sha256Hash")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("LAC.Domain.DocumentAward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("DocumentId", "AwardId")
                        .IsUnique();

                    b.ToTable("DocumentAwards");
                });

            modelBuilder.Entity("LAC.Domain.DocumentKhasra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KhasraId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KhasraId");

                    b.HasIndex("DocumentId", "KhasraId")
                        .IsUnique();

                    b.ToTable("DocumentKhasras");
                });

            modelBuilder.Entity("LAC.Domain.DocumentNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("DocumentId", "NotificationId")
                        .IsUnique();

                    b.ToTable("DocumentNotifications");
                });

            modelBuilder.Entity("LAC.Domain.DocumentVillage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.HasIndex("DocumentId", "VillageId")
                        .IsUnique();

                    b.ToTable("DocumentVillages");
                });

            modelBuilder.Entity("LAC.Domain.DocumentVillageLR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VillageLRId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageLRId");

                    b.HasIndex("DocumentId", "VillageLRId")
                        .IsUnique();

                    b.ToTable("DocumentVillageLRs");
                });

            modelBuilder.Entity("LAC.Domain.Khasra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaUnit")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DisplayNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KillaNumber")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RectangleNumber")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SubdivisionNumber")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId", "NormalizedNumber")
                        .IsUnique();

                    b.ToTable("Khasras");
                });

            modelBuilder.Entity("LAC.Domain.LREntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaUnit")
                        .HasColumnType("text");

                    b.Property<Guid?>("AwardId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("KhasraId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ParsedArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("RawAreaText")
                        .HasColumnType("text");

                    b.Property<string>("RawKhasraText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawRemarks")
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int?>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("Section4NotificationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Section6NotificationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VillageLRId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AwardId");

                    b.HasIndex("KhasraId");

                    b.HasIndex("Section4NotificationId");

                    b.HasIndex("Section6NotificationId");

                    b.HasIndex("VillageLRId");

                    b.ToTable("LREntries");
                });

            modelBuilder.Entity("LAC.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AcquisitionProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("GazetteDetails")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NotificationDate")
                        .HasColumnType("date");

                    b.Property<string>("NotificationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<string>("SectionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AcquisitionProjectId");

                    b.HasIndex("SectionType", "NotificationNumber")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("LAC.Domain.NotificationKhasra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaUnit")
                        .HasColumnType("text");

                    b.Property<Guid>("KhasraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("NotifiedArea")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KhasraId");

                    b.HasIndex("NotificationId", "KhasraId")
                        .IsUnique();

                    b.ToTable("NotificationKhasra");
                });

            modelBuilder.Entity("LAC.Domain.SubDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId", "Name")
                        .IsUnique();

                    b.ToTable("SubDivisions");
                });

            modelBuilder.Entity("LAC.Domain.Village", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubDivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SubDivisionId", "Name")
                        .IsUnique();

                    b.ToTable("Villages");
                });

            modelBuilder.Entity("LAC.Domain.VillageLR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegisterReference")
                        .HasColumnType("text");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("VillageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VillageId");

                    b.ToTable("VillageLRs");
                });

            modelBuilder.Entity("LAC.Domain.Award", b =>
                {
                    b.HasOne("LAC.Domain.AcquisitionProject", "AcquisitionProject")
                        .WithMany()
                        .HasForeignKey("AcquisitionProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcquisitionProject");
                });

            modelBuilder.Entity("LAC.Domain.AwardKhasra", b =>
                {
                    b.HasOne("LAC.Domain.Award", "Award")
                        .WithMany("KhasraLinks")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.Khasra", "Khasra")
                        .WithMany("AwardLinks")
                        .HasForeignKey("KhasraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Khasra");
                });

            modelBuilder.Entity("LAC.Domain.DocumentAward", b =>
                {
                    b.HasOne("LAC.Domain.Award", "Award")
                        .WithMany("DocumentRelationships")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.Document", "Document")
                        .WithMany("AwardLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("LAC.Domain.DocumentKhasra", b =>
                {
                    b.HasOne("LAC.Domain.Document", "Document")
                        .WithMany("KhasraLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.Khasra", "Khasra")
                        .WithMany("DocumentRelationships")
                        .HasForeignKey("KhasraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Khasra");
                });

            modelBuilder.Entity("LAC.Domain.DocumentNotification", b =>
                {
                    b.HasOne("LAC.Domain.Document", "Document")
                        .WithMany("NotificationLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.Notification", "Notification")
                        .WithMany("DocumentRelationships")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("LAC.Domain.DocumentVillage", b =>
                {
                    b.HasOne("LAC.Domain.Document", "Document")
                        .WithMany("VillageLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.Village", "Village")
                        .WithMany("DocumentRelationships")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Village");
                });

            modelBuilder.Entity("LAC.Domain.DocumentVillageLR", b =>
                {
                    b.HasOne("LAC.Domain.Document", "Document")
                        .WithMany("VillageLRLinks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.VillageLR", "VillageLR")
                        .WithMany("DocumentRelationships")
                        .HasForeignKey("VillageLRId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("VillageLR");
                });

            modelBuilder.Entity("LAC.Domain.Khasra", b =>
                {
                    b.HasOne("LAC.Domain.Village", "Village")
                        .WithMany("Khasras")
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("LAC.Domain.LREntry", b =>
                {
                    b.HasOne("LAC.Domain.Award", "Award")
                        .WithMany()
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LAC.Domain.Khasra", "Khasra")
                        .WithMany()
                        .HasForeignKey("KhasraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LAC.Domain.Notification", "Section4Notification")
                        .WithMany()
                        .HasForeignKey("Section4NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LAC.Domain.Notification", "Section6Notification")
                        .WithMany()
                        .HasForeignKey("Section6NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LAC.Domain.VillageLR", "VillageLR")
                        .WithMany("Entries")
                        .HasForeignKey("VillageLRId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Award");

                    b.Navigation("Khasra");

                    b.Navigation("Section4Notification");

                    b.Navigation("Section6Notification");

                    b.Navigation("VillageLR");
                });

            modelBuilder.Entity("LAC.Domain.Notification", b =>
                {
                    b.HasOne("LAC.Domain.AcquisitionProject", "AcquisitionProject")
                        .WithMany()
                        .HasForeignKey("AcquisitionProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcquisitionProject");
                });

            modelBuilder.Entity("LAC.Domain.NotificationKhasra", b =>
                {
                    b.HasOne("LAC.Domain.Khasra", "Khasra")
                        .WithMany("NotificationLinks")
                        .HasForeignKey("KhasraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LAC.Domain.Notification", "Notification")
                        .WithMany("KhasraLinks")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Khasra");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("LAC.Domain.SubDivision", b =>
                {
                    b.HasOne("LAC.Domain.District", "District")
                        .WithMany("SubDivisions")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("LAC.Domain.Village", b =>
                {
                    b.HasOne("LAC.Domain.SubDivision", "SubDivision")
                        .WithMany("Villages")
                        .HasForeignKey("SubDivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubDivision");
                });

            modelBuilder.Entity("LAC.Domain.VillageLR", b =>
                {
                    b.HasOne("LAC.Domain.Village", "Village")
                        .WithMany()
                        .HasForeignKey("VillageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Village");
                });

            modelBuilder.Entity("LAC.Domain.Award", b =>
                {
                    b.Navigation("DocumentRelationships");

                    b.Navigation("KhasraLinks");
                });

            modelBuilder.Entity("LAC.Domain.District", b =>
                {
                    b.Navigation("SubDivisions");
                });

            modelBuilder.Entity("LAC.Domain.Document", b =>
                {
                    b.Navigation("AwardLinks");

                    b.Navigation("KhasraLinks");

                    b.Navigation("NotificationLinks");

                    b.Navigation("VillageLRLinks");

                    b.Navigation("VillageLinks");
                });

            modelBuilder.Entity("LAC.Domain.Khasra", b =>
                {
                    b.Navigation("AwardLinks");

                    b.Navigation("DocumentRelationships");

                    b.Navigation("NotificationLinks");
                });

            modelBuilder.Entity("LAC.Domain.Notification", b =>
                {
                    b.Navigation("DocumentRelationships");

                    b.Navigation("KhasraLinks");
                });

            modelBuilder.Entity("LAC.Domain.SubDivision", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("LAC.Domain.Village", b =>
                {
                    b.Navigation("DocumentRelationships");

                    b.Navigation("Khasras");
                });

            modelBuilder.Entity("LAC.Domain.VillageLR", b =>
                {
                    b.Navigation("DocumentRelationships");

                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
