using LAC.Domain;
using LAC.Infrastructure;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.EntityFrameworkCore;

var b=WebApplication.CreateBuilder(args);
b.Services.AddProblemDetails(); b.Services.AddEndpointsApiExplorer(); b.Services.AddSwaggerGen();
b.Services.AddDbContext<LacDbContext>(o=>o.UseNpgsql(b.Configuration.GetConnectionString("DefaultConnection")));
b.Services.AddScoped<IDocumentStorage,LocalDocumentStorage>(); b.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.WithOrigins("http://localhost:5173").AllowAnyHeader().AllowAnyMethod()));
var app=b.Build(); app.UseExceptionHandler(x=>x.Run(async c=>await Results.Problem(statusCode:500,title:"Unexpected server error").ExecuteAsync(c))); app.UseSwagger(); app.UseSwaggerUI(); app.UseCors();
using(var scope=app.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<LacDbContext>(); await db.Database.MigrateAsync(); await SeedData.SeedAsync(db,default);}
var api=app.MapGroup("/api");
api.MapGet("/districts",async(LacDbContext db,CancellationToken ct)=>await db.Districts.OrderBy(x=>x.Name).Select(x=>new {x.Id,x.Name,subDivisionCount=x.SubDivisions.Count}).ToListAsync(ct));
api.MapGet("/districts/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.Districts.Where(x=>x.Id==id).Select(x=>new {x.Id,x.Name,subDivisions=x.SubDivisions.OrderBy(s=>s.Name).Select(s=>new{s.Id,s.Name})}).FirstOrDefaultAsync(ct) is { } d?Results.Ok(d):Results.NotFound());
api.MapGet("/subdivisions/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.SubDivisions.Where(x=>x.Id==id).Select(x=>new{x.Id,x.Name,district=new{x.District.Id,x.District.Name},villages=x.Villages.OrderBy(v=>v.Name).Select(v=>new{v.Id,v.Name})}).FirstOrDefaultAsync(ct) is { } s?Results.Ok(s):Results.NotFound());
api.MapGet("/villages/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.Villages.Where(x=>x.Id==id).Select(v=>new {v.Id,v.Name,subDivision=new{v.SubDivision.Id,v.SubDivision.Name,district=new{v.SubDivision.District.Id,v.SubDivision.District.Name}},totalKhasras=v.Khasras.Count,linkedAwards=v.Khasras.SelectMany(k=>k.AwardLinks).Select(a=>a.AwardId).Distinct().Count(),lrAvailable=db.VillageLRs.Any(l=>l.VillageId==v.Id),documentCount=v.DocumentRelationships.Count,khasras=v.Khasras.OrderBy(k=>k.DisplayNumber).Select(k=>new{k.Id,k.DisplayNumber,k.TotalArea,k.AreaUnit,awards=k.AwardLinks.Select(a=>new{a.Award.Id,a.Award.AwardNumber,a.AcquisitionStatus})})}).FirstOrDefaultAsync(ct) is { } v?Results.Ok(v):Results.NotFound());
api.MapGet("/khasras/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.Khasras.Where(k=>k.Id==id).Select(k=>new{k.Id,k.DisplayNumber,k.NormalizedNumber,k.RectangleNumber,k.KillaNumber,k.SubdivisionNumber,k.TotalArea,k.AreaUnit,k.Remarks,village=new{k.Village.Id,k.Village.Name,subDivision=new{k.Village.SubDivision.Id,k.Village.SubDivision.Name,district=new{k.Village.SubDivision.District.Id,k.Village.SubDivision.District.Name}}},notifications=k.NotificationLinks.Select(n=>new{n.Notification.Id,n.Notification.NotificationNumber,n.Notification.SectionType,n.NotifiedArea,n.AreaUnit}),awards=k.AwardLinks.Select(a=>new{a.Award.Id,a.Award.AwardNumber,a.AcquiredArea,a.AreaUnit,a.AcquisitionStatus})}).FirstOrDefaultAsync(ct) is { } k?Results.Ok(k):Results.NotFound());
api.MapGet("/awards",async(int page,LacDbContext db,CancellationToken ct)=>await db.Awards.OrderByDescending(a=>a.AwardDate).Skip(Math.Max(page,0)*50).Take(50).Select(a=>new{a.Id,a.AwardNumber,a.AwardDate,a.Status,a.AwardType}).ToListAsync(ct));
api.MapGet("/awards/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.Awards.Where(a=>a.Id==id).Select(a=>new {a.Id,a.AwardNumber,a.AwardDate,a.AwardType,a.Status,a.ActRegime,a.Remarks,project=a.AcquisitionProject==null?null:new{a.AcquisitionProject.Id,a.AcquisitionProject.Name,a.AcquisitionProject.RequiringAgency},khasras=a.KhasraLinks.Select(k=>new{k.Khasra.Id,k.Khasra.DisplayNumber,village=k.Khasra.Village.Name,k.AcquiredArea,k.AreaUnit,k.AcquisitionStatus})}).FirstOrDefaultAsync(ct) is { } a?Results.Ok(a):Results.NotFound());
api.MapGet("/notifications",async(LacDbContext db,CancellationToken ct)=>await db.Notifications.OrderByDescending(x=>x.NotificationDate).Take(50).Select(n=>new{n.Id,n.NotificationNumber,n.SectionType,n.NotificationDate}).ToListAsync(ct));
api.MapGet("/notifications/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.Notifications.Where(n=>n.Id==id).Select(n=>new{n.Id,n.NotificationNumber,n.SectionType,n.NotificationDate,n.GazetteDetails,n.Remarks,khasras=n.KhasraLinks.Select(k=>new{k.Khasra.Id,k.Khasra.DisplayNumber,k.NotifiedArea,k.AreaUnit})}).FirstOrDefaultAsync(ct) is {} n?Results.Ok(n):Results.NotFound());
api.MapGet("/search",async(string q,LacDbContext db,CancellationToken ct)=>{var term=q.Trim().ToUpper();if(term.Length<2)return Results.Ok(Array.Empty<object>()); var v=await db.Villages.Where(x=>x.Name.ToUpper().Contains(term)).Take(8).Select(x=>new SearchResult("Village",x.Id,x.Name,null)).ToListAsync(ct);var k=await db.Khasras.Where(x=>x.NormalizedNumber.Contains(term)).Take(12).Select(x=>new SearchResult("Khasra",x.Id,x.DisplayNumber,x.Village.Name)).ToListAsync(ct);var a=await db.Awards.Where(x=>x.AwardNumber.ToUpper().Contains(term)).Take(8).Select(x=>new SearchResult("Award",x.Id,x.AwardNumber,null)).ToListAsync(ct);return Results.Ok(v.Concat(k).Concat(a));});
api.MapGet("/village-lrs/{id:guid}",async(Guid id,LacDbContext db,CancellationToken ct)=>await db.VillageLRs.Where(x=>x.Id==id).Include(x=>x.Entries).FirstOrDefaultAsync(ct) is {} l?Results.Ok(l):Results.NotFound());
api.MapPost("/village-lrs/{id:guid}/entries",async(Guid id,CreateLrEntry dto,LacDbContext db,CancellationToken ct)=>{if(string.IsNullOrWhiteSpace(dto.RawKhasraText))return Results.ValidationProblem(new Dictionary<string,string[]>{{"rawKhasraText",["Required."]}});if(!await db.VillageLRs.AnyAsync(x=>x.Id==id,ct))return Results.NotFound();var row=new LREntry{VillageLRId=id,RawKhasraText=dto.RawKhasraText,RawAreaText=dto.RawAreaText,RawRemarks=dto.RawRemarks,KhasraId=dto.KhasraId,AwardId=dto.AwardId,Section4NotificationId=dto.Section4NotificationId,Section6NotificationId=dto.Section6NotificationId,VerificationStatus=VerificationStatus.Draft};db.Add(row);await db.SaveChangesAsync(ct);return Results.Created($"/api/lr-entries/{row.Id}",new{id=row.Id});});
app.Run(); record SearchResult(string Type,Guid Id,string Label,string? Context); record CreateLrEntry(string RawKhasraText,string? RawAreaText,string? RawRemarks,Guid? KhasraId,Guid? AwardId,Guid? Section4NotificationId,Guid? Section6NotificationId);
