export type BulkFormat = "auto" | "shorthand" | "columns3" | "columns4" | "transposed" | "separate";
export type RevenueArea = { bigha: number; biswa: number; biswansi: number };
export type BulkRow = { index: number; sourceRow: number; reference: string; cells: string[]; value: RevenueArea | null; error: string | null };
export type BulkParseResult = { format: BulkFormat; label: string; rows: BulkRow[]; unresolved: boolean; recordCount: number; validCount: number; errorCount: number };
export const BULK_FORMATS: Record<BulkFormat, string>;
export function tokenizeUnitList(text: string): string[];
export function detectBulkRevenueFormat(text: string): BulkFormat | null;
export function parseRevenueShorthandBulk(text: string): BulkParseResult;
export function parseRevenueColumnTable(text: string): BulkParseResult;
export function parseRevenueReferenceTable(text: string): BulkParseResult;
export function parseTransposedRevenueRows(text: string): BulkParseResult;
export function parseSeparateUnitLists(bigha: string, biswa: string, biswansi: string): BulkParseResult;
export function parseBulkRevenue(text: string, selectedFormat?: BulkFormat): BulkParseResult;
export function sumBulkRevenueRows(parsed: BulkParseResult): { records: number; totalBiswansi: number; revenue: RevenueArea; totals: { totalBigha: number; totalBiswa: number; totalBiswansi: number }; sqm: number; conversions: Record<string, number> };
export function normalizedRowsForExcel(parsed: BulkParseResult): string;
