import { useEffect, useMemo, useState } from "react";
import { AREA_UNITS, LENGTH_UNITS, addRevenueAreas, allAreaConversions, areaToSqm, fromTotalBiswansi, lengthToMetres, metresToLength, normalizeRevenueTotal, parseRevenueShorthand, revenueToSqm, revenueTotals, sqmToArea, sqmToRevenue, subtractRevenueAreas, validateRevenue } from "./landConversions";
import { evaluateExpression } from "./arithmetic";
import "./calculator.css";

type Revenue = { bigha: number; biswa: number; biswansi: number };
type RevenueRow = { id: number; bigha: string; biswa: string; biswansi: string; shorthand: string; shorthandMode: boolean };
let revenueRowSequence = 0;
const display = (value: number, digits = 4) => Number.isFinite(value) ? value.toLocaleString("en-IN", { maximumFractionDigits: digits }) : "—";
const compact = (value: Revenue) => `${value.bigha}-${value.biswa}-${value.biswansi}`;
const formal = (value: Revenue) => `${value.bigha} Bigha ${String(value.biswa).padStart(2, "0")} Biswa ${String(value.biswansi).padStart(2, "0")} Biswansi`;
const newRow = (): RevenueRow => ({ id: ++revenueRowSequence, bigha: "", biswa: "", biswansi: "", shorthand: "", shorthandMode: false });
const rowRevenue = (row: RevenueRow) => row.shorthandMode ? parseRevenueShorthand(row.shorthand) : validateRevenue(row.bigha || 0, row.biswa || 0, row.biswansi || 0);
const copy = async (text: string) => { await navigator.clipboard?.writeText(text); };

function NormalCalculator() {
  const [expression, setExpression] = useState(""); const [result, setResult] = useState("");
  const calculate = () => { try { setResult(display(evaluateExpression(expression), 10)); } catch (error) { setResult(error instanceof Error ? error.message : "Invalid expression."); } };
  useEffect(() => { const key = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target?.matches("input, textarea, select, [contenteditable='true']")) return; if (/^[0-9.+\-*/%()]$/.test(event.key)) setExpression((value) => value + event.key); else if (event.key === "Enter") { event.preventDefault(); calculate(); } else if (event.key === "Backspace") setExpression((value) => value.slice(0, -1)); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  return <div className="calc-normal"><input aria-label="Calculator expression" value={expression} onChange={(event) => setExpression(event.target.value)} placeholder="0" /><output aria-live="polite">{result || "0"}</output><div className="calc-keypad">{["7", "8", "9", "÷", "4", "5", "6", "×", "1", "2", "3", "−", "0", ".", "%", "+", "(", ")", "⌫", "C", "="].map((key) => <button key={key} className={key === "=" ? "primary" : ""} onClick={() => key === "=" ? calculate() : key === "C" ? (setExpression(""), setResult("")) : key === "⌫" ? setExpression((v) => v.slice(0, -1)) : setExpression((v) => v + ({ "÷": "/", "×": "*", "−": "-" }[key] || key))}>{key}</button>)}</div></div>;
}

function RevenueRowInput({ row, onChange, removable, onRemove }: { row: RevenueRow; onChange: (row: RevenueRow) => void; removable: boolean; onRemove: () => void }) {
  const set = (field: keyof RevenueRow, value: string | boolean) => onChange({ ...row, [field]: value });
  return <div className="revenue-row"><div className="calc-entry-tabs"><button className={!row.shorthandMode ? "active" : ""} onClick={() => set("shorthandMode", false)}>Fields</button><button className={row.shorthandMode ? "active" : ""} onClick={() => set("shorthandMode", true)}>Shorthand</button></div>{row.shorthandMode ? <label className="revenue-short">Bigha-Biswa-Biswansi<input aria-label="Revenue shorthand" value={row.shorthand} onChange={e => set("shorthand", e.target.value)} placeholder="20-19-09" /></label> : <div className="mixed-fields">{(["bigha", "biswa", "biswansi"] as const).map(key => <label key={key}>{key}<input aria-label={key} min="0" type="number" value={row[key]} onChange={e => set(key, e.target.value)} /></label>)}</div>}{removable && <button className="remove-row" onClick={onRemove}>Remove area</button>}</div>;
}

function RevenueArithmetic() {
  const [operation, setOperation] = useState<"add" | "subtract">("add"); const [rows, setRows] = useState<RevenueRow[]>([newRow(), newRow()]); const [normalizerValue, setNormalizerValue] = useState("152"); const [normalizerUnit, setNormalizerUnit] = useState<"bigha" | "biswa" | "biswansi">("biswa");
  const parsed = useMemo(() => rows.map(rowRevenue), [rows]); const invalid = parsed.find(result => !result.valid);
  const result = useMemo(() => { if (invalid) return { error: invalid.error }; try { if (operation === "add") return { value: addRevenueAreas(parsed.map(item => item.value)) }; const subtrahend = parsed.slice(1).reduce((total, item) => addRevenueAreas([total, item.value]), fromTotalBiswansi(0)); return { value: subtractRevenueAreas(parsed[0].value, subtrahend) }; } catch (error) { return { error: error instanceof Error ? error.message : "Unable to calculate." }; } }, [invalid, operation, parsed]);
  let normalized: Revenue | null = null; let normalizerError = ""; try { normalized = normalizeRevenueTotal(normalizerValue, normalizerUnit); } catch (error) { normalizerError = error instanceof Error ? error.message : "Invalid total."; }
  const changeRow = (index: number, row: RevenueRow) => setRows(rows.map((item, current) => current === index ? row : item)); const totals = result.value ? revenueTotals(result.value) : null;
  return <div className="converter revenue-arithmetic"><div className="calc-entry-tabs"><button className={operation === "add" ? "active" : ""} onClick={() => setOperation("add")}>Addition</button><button className={operation === "subtract" ? "active" : ""} onClick={() => setOperation("subtract")}>Subtraction</button></div><p className="calc-note">{operation === "add" ? "Add all listed Award / Khasra areas." : "Subtract every later row from the first area. Negative totals are rejected."}</p><div className="revenue-headings"><span>Bigha</span><span>Biswa</span><span>Biswansi</span></div>{rows.map((row, index) => <RevenueRowInput key={row.id} row={row} onChange={next => changeRow(index, next)} removable={rows.length > 2} onRemove={() => setRows(rows.filter((_, current) => current !== index))} />)}{operation === "add" && <button onClick={() => setRows([...rows, newRow()])}>+ Add another area</button>}{result.error && <p className="calc-error">{result.error}</p>}{result.value && totals && <section className="calc-result revenue-total"><span>TOTAL</span><strong>{formal(result.value)}</strong><b>{compact(result.value)}</b><p>Total Bigha: {display(totals.totalBigha, 10)} · Total Biswa: {display(totals.totalBiswa, 10)} · Total Biswansi: {totals.totalBiswansi}</p><div><button onClick={() => copy(formal(result.value!))}>Copy formal</button><button onClick={() => copy(compact(result.value!))}>Copy shorthand</button><button onClick={() => copy(`${formal(result.value!)}\n${compact(result.value!)}`)}>Copy Total</button></div></section>}<section className="quick-normalizer"><h3>Quick Revenue Normalizer</h3><p>Totals may exceed 19 here; they are normalized into revenue notation.</p><div className="converter-row"><label>Total<input type="number" min="0" step="1" value={normalizerValue} onChange={e => setNormalizerValue(e.target.value)} /></label><label>Unit<select value={normalizerUnit} onChange={e => setNormalizerUnit(e.target.value as typeof normalizerUnit)}><option value="bigha">Bigha</option><option value="biswa">Biswa</option><option value="biswansi">Biswansi</option></select></label></div>{normalizerError && <p className="calc-error">{normalizerError}</p>}{normalized && <div className="normalizer-result"><strong>{formal(normalized)}</strong><span>{compact(normalized)}</span><button onClick={() => copy(`${formal(normalized!)}\n${compact(normalized!)}`)}>Copy Total</button></div>}</section></div>;
}

function AreaConverter() {
  const [from, setFrom] = useState("bigha"); const [to, setTo] = useState("sqm"); const [value, setValue] = useState("1"); const [mode, setMode] = useState<"single" | "mixed" | "short">("single"); const [mixed, setMixed] = useState({ bigha: "", biswa: "", biswansi: "" }); const [short, setShort] = useState("");
  const isRevenueSource = ["bigha", "biswa", "biswansi"].includes(from);
  const selectFrom = (next: string) => { setFrom(next); if (!["bigha", "biswa", "biswansi"].includes(next)) setMode("single"); };
  const parsed = mode === "mixed" ? validateRevenue(mixed.bigha || 0, mixed.biswa || 0, mixed.biswansi || 0) : mode === "short" ? parseRevenueShorthand(short) : null;
  const error = parsed && !parsed.valid ? parsed.error : ""; const sqm = mode === "mixed" || mode === "short" ? (parsed?.valid ? revenueToSqm(parsed.value) : null) : areaToSqm(value, from); const all = sqm === null ? null : allAreaConversions(sqm);
  return <div className="converter"><div className="converter-row"><label>From<select value={from} onChange={e => selectFrom(e.target.value)}>{Object.entries(AREA_UNITS).map(([id, u]) => <option key={id} value={id}>{u.label}</option>)}</select></label><button className="swap" onClick={() => { const old = from; selectFrom(to); setTo(old); }}>⇄</button><label>To<select value={to} onChange={e => setTo(e.target.value)}>{Object.entries(AREA_UNITS).map(([id, u]) => <option key={id} value={id}>{u.label}</option>)}</select></label></div>{isRevenueSource && <div className="calc-entry-tabs"><button className={mode === "single" ? "active" : ""} onClick={() => setMode("single")}>Single value</button><button className={mode === "mixed" ? "active" : ""} onClick={() => setMode("mixed")}>Bigha-Biswa-Biswansi</button><button className={mode === "short" ? "active" : ""} onClick={() => setMode("short")}>Shorthand</button></div>}{mode === "single" ? <input type="number" min="0" value={value} onChange={e => setValue(e.target.value)} /> : mode === "short" ? <input value={short} onChange={e => setShort(e.target.value)} placeholder="2-9-1" /> : <div className="mixed-fields">{(["bigha", "biswa", "biswansi"] as const).map(key => <label key={key}>{key}<input min="0" type="number" value={mixed[key]} onChange={e => setMixed({ ...mixed, [key]: e.target.value })} /></label>)}</div>}{error && <p className="calc-error">{error}</p>}{sqm !== null && all && <><section className="calc-result"><span>{AREA_UNITS[to].label}</span><strong>{display(sqmToArea(sqm, to), to === "hectare" || to === "acre" ? 6 : to === "sqkm" ? 8 : 4)}</strong><button onClick={() => copy(String(sqmToArea(sqm, to)))}>Copy result</button></section><section className="all-conversions"><div><b>Revenue format</b><span>{compact(sqmToRevenue(sqm))}</span></div>{Object.entries(all).map(([id, result]) => <div key={id}><b>{AREA_UNITS[id].label}</b><span>{display(result, id === "hectare" || id === "acre" ? 6 : id === "sqkm" ? 8 : 4)}</span></div>)}<button onClick={() => copy(`Revenue: ${compact(sqmToRevenue(sqm))}\n${Object.entries(all).map(([id, n]) => `${AREA_UNITS[id].label}: ${n}`).join("\n")}`)}>Copy all conversions</button></section></>}</div>;
}

function LengthConverter() { const [from, setFrom] = useState("ghatta"), [to, setTo] = useState("metre"), [value, setValue] = useState("1"); const metres = lengthToMetres(value, from); return <div className="converter"><div className="converter-row"><label>From<select value={from} onChange={e => setFrom(e.target.value)}>{Object.entries(LENGTH_UNITS).map(([id, u]) => <option key={id} value={id}>{u.label}</option>)}</select></label><button className="swap" onClick={() => { const old = from; setFrom(to); setTo(old); }}>⇄</button><label>To<select value={to} onChange={e => setTo(e.target.value)}>{Object.entries(LENGTH_UNITS).map(([id, u]) => <option key={id} value={id}>{u.label}</option>)}</select></label></div><input type="number" min="0" value={value} onChange={e => setValue(e.target.value)} />{metres !== null && <section className="calc-result"><span>{LENGTH_UNITS[to].label}</span><strong>{display(metresToLength(metres, to), 6)}</strong><p>1 square Ghatta is a derived area: 68.0625 sq ft.</p></section>}</div>; }

export function CalculatorModal({ open, onClose }: { open: boolean; onClose: () => void }) { const [tab, setTab] = useState("calculator"); const [basis, setBasis] = useState(false); useEffect(() => { const key = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); }; if (open) window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [onClose, open]); if (!open) return null; const content = tab === "calculator" ? <NormalCalculator /> : tab === "area" ? <AreaConverter /> : tab === "revenue" ? <RevenueArithmetic /> : <LengthConverter />; return <div className="calculator-backdrop" onMouseDown={onClose}><section className="calculator-modal" role="dialog" aria-modal="true" aria-label="Land and Area Calculator" onMouseDown={e => e.stopPropagation()}><header><h2>Calculator</h2><button onClick={onClose} aria-label="Close calculator">×</button></header><nav>{[["calculator", "Calculator"], ["area", "Area"], ["revenue", "Revenue Arithmetic"], ["length", "Length"]].map(([id, label]) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}>{label}</button>)}</nav>{content}<footer><button className="basis-toggle" onClick={() => setBasis(!basis)}>Delhi Revenue Conversion Basis {basis ? "▾" : "▸"}</button>{basis && <div className="basis"><p>1 Bigha = 20 Biswa = 843 sq m · 1 Biswa = 20 Biswansi = 42.15 sq m · 1 Biswansi = 2.1075 sq m.</p><p>Revenue arithmetic uses exact integers: 1 Bigha = 400 Biswansi.</p><small>GNCTD published tables include rounded conventional values. This calculator uses the Delhi LAC revenue profile above as its canonical revenue basis and does not mix conflicting rounded factors.</small></div>}</footer></section></div>; }
