import { useEffect, useState } from "react";
import { AREA_UNITS, LENGTH_UNITS, allAreaConversions, areaToSqm, lengthToMetres, metresToLength, parseRevenueShorthand, revenueToSqm, sqmToArea, sqmToRevenue, validateRevenue } from "./landConversions";
import { evaluateExpression } from "./arithmetic";
import "./calculator.css";

const display = (value: number, digits = 4) => Number.isFinite(value) ? value.toLocaleString("en-IN", { maximumFractionDigits: digits }) : "—";
const revenueText = (sqm: number) => { const r = sqmToRevenue(sqm); return `${r.bigha}-${r.biswa}-${display(r.biswansi, 4)}`; };

function NormalCalculator() {
  const [expression, setExpression] = useState(""); const [result, setResult] = useState("");
  const calculate = () => { try { setResult(display(evaluateExpression(expression), 10)); } catch (error) { setResult(error instanceof Error ? error.message : "Invalid expression."); } };
  useEffect(() => { const key = (event: KeyboardEvent) => { if (/^[0-9.+\-*/%()]$/.test(event.key)) setExpression((value) => value + event.key); else if (event.key === "Enter") { event.preventDefault(); calculate(); } else if (event.key === "Backspace") setExpression((value) => value.slice(0, -1)); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); });
  return <div className="calc-normal"><input aria-label="Calculator expression" value={expression} onChange={(event) => setExpression(event.target.value)} placeholder="0" /><output aria-live="polite">{result || "0"}</output><div className="calc-keypad">{["7","8","9","÷","4","5","6","×","1","2","3","−","0",".","%","+","(",")","⌫","C","="].map((key) => <button key={key} className={key === "=" ? "primary" : ""} onClick={() => key === "=" ? calculate() : key === "C" ? (setExpression(""), setResult("")) : key === "⌫" ? setExpression((v) => v.slice(0,-1)) : setExpression((v) => v + ({ "÷":"/", "×":"*", "−":"-" }[key] || key))}>{key}</button>)}</div></div>;
}

function AreaConverter() {
  const [from, setFrom] = useState("bigha"), [to, setTo] = useState("sqm"), [value, setValue] = useState("1"), [mode, setMode] = useState<"single"|"mixed"|"short">("single"), [mixed, setMixed] = useState({ bigha:"", biswa:"", biswansi:"" }), [short, setShort] = useState("");
  const parsed = mode === "mixed" ? validateRevenue(mixed.bigha || 0, mixed.biswa || 0, mixed.biswansi || 0) : mode === "short" ? parseRevenueShorthand(short) : null;
  const error = parsed && !parsed.valid ? parsed.error : "";
  const sqm = mode === "mixed" || mode === "short" ? (parsed?.valid ? revenueToSqm(parsed.value) : null) : areaToSqm(value, from);
  const all = sqm === null ? null : allAreaConversions(sqm);
  const copy = async (text: string) => { await navigator.clipboard?.writeText(text); };
  return <div className="converter"><div className="converter-row"><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{Object.entries(AREA_UNITS).map(([id,u])=><option key={id} value={id}>{u.label}</option>)}</select></label><button className="swap" onClick={()=>{ const old=from; setFrom(to); setTo(old); }}>⇄</button><label>To<select value={to} onChange={e=>setTo(e.target.value)}>{Object.entries(AREA_UNITS).map(([id,u])=><option key={id} value={id}>{u.label}</option>)}</select></label></div><div className="calc-entry-tabs"><button className={mode==="single"?"active":""} onClick={()=>setMode("single")}>Single value</button><button className={mode==="mixed"?"active":""} onClick={()=>setMode("mixed")}>Bigha-Biswa-Biswansi</button><button className={mode==="short"?"active":""} onClick={()=>setMode("short")}>Shorthand</button></div>{mode === "single" ? <input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} /> : mode === "short" ? <input value={short} onChange={e=>setShort(e.target.value)} placeholder="2-9-1" /> : <div className="mixed-fields">{(["bigha","biswa","biswansi"] as const).map(key=><label key={key}>{key}<input min="0" type="number" value={mixed[key]} onChange={e=>setMixed({...mixed,[key]:e.target.value})}/></label>)}</div>}{error && <p className="calc-error">{error}</p>}{sqm !== null && all && <><section className="calc-result"><span>{AREA_UNITS[to].label}</span><strong>{display(sqmToArea(sqm,to), to === "hectare" || to === "acre" ? 6 : to === "sqkm" ? 8 : 4)}</strong><button onClick={()=>copy(String(sqmToArea(sqm,to)))}>Copy result</button></section><section className="all-conversions"><div><b>Revenue format</b><span>{revenueText(sqm)}</span></div>{Object.entries(all).map(([id,result])=><div key={id}><b>{AREA_UNITS[id].label}</b><span>{display(result, id === "hectare" || id === "acre" ? 6 : id === "sqkm" ? 8 : 4)}</span></div>)}<button onClick={()=>copy(`Revenue: ${revenueText(sqm)}\n${Object.entries(all).map(([id,n])=>`${AREA_UNITS[id].label}: ${n}`).join("\n")}`)}>Copy all conversions</button></section></>}</div>;
}

function LengthConverter() { const [from,setFrom]=useState("ghatta"),[to,setTo]=useState("metre"),[value,setValue]=useState("1"); const metres=lengthToMetres(value,from); return <div className="converter"><div className="converter-row"><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{Object.entries(LENGTH_UNITS).map(([id,u])=><option key={id} value={id}>{u.label}</option>)}</select></label><button className="swap" onClick={()=>{const old=from;setFrom(to);setTo(old)}}>⇄</button><label>To<select value={to} onChange={e=>setTo(e.target.value)}>{Object.entries(LENGTH_UNITS).map(([id,u])=><option key={id} value={id}>{u.label}</option>)}</select></label></div><input type="number" min="0" value={value} onChange={e=>setValue(e.target.value)} />{metres !== null && <section className="calc-result"><span>{LENGTH_UNITS[to].label}</span><strong>{display(metresToLength(metres,to),6)}</strong><p>1 square Ghatta is a derived area: 68.0625 sq ft.</p></section>}</div>; }

export function CalculatorModal({ open, onClose }: { open: boolean; onClose: () => void }) { const [tab,setTab]=useState("calculator"); const [basis,setBasis]=useState(false); useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()}; if(open) window.addEventListener("keydown",key); return()=>window.removeEventListener("keydown",key)},[onClose,open]); if(!open)return null; return <div className="calculator-backdrop" onMouseDown={onClose}><section className="calculator-modal" role="dialog" aria-modal="true" aria-label="Land and Area Calculator" onMouseDown={e=>e.stopPropagation()}><header><h2>Calculator</h2><button onClick={onClose} aria-label="Close calculator">×</button></header><nav>{[["calculator","Calculator"],["area","Area"],["length","Length"]].map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}</button>)}</nav>{tab==="calculator"?<NormalCalculator/>:tab==="area"?<AreaConverter/>:<LengthConverter/>}<footer><button className="basis-toggle" onClick={()=>setBasis(!basis)}>Delhi Revenue Conversion Basis {basis?"▾":"▸"}</button>{basis&&<div className="basis"><p>1 Bigha = 20 Biswa = 843 sq m · 1 Biswa = 20 Biswansi = 42.15 sq m · 1 Biswansi = 2.1075 sq m.</p><p>Official GNCTD references: 1 Acre = 4 Bigha 16 Biswa / 4840 sq yd; 1 Bigha = 1008 sq yd; 1 Biswa = 50 sq yd; 1 Ghatta = 8.25 ft; 1 hectare = 10,000 sq m = 0.01 sq km ≈ 2.471 acre.</p><small>GNCTD published tables include rounded conventional values. This calculator uses the Delhi LAC revenue profile above as its canonical revenue basis and does not mix conflicting rounded factors.</small></div>}</footer></section></div>; }
