namespace LAC.Infrastructure;

using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using ClosedXML.Excel;
using LAC.Domain;
using Microsoft.EntityFrameworkCore;

public sealed record CourtImportBatchDto(Guid Id, string Status, string SourceSheetName, int TotalRows, int ValidRows, int NeedsReviewRows, int ConflictRows, int InvalidRows, string? FailureMessage, DateTimeOffset CreatedAt);
public sealed record CourtImportRowDto(Guid Id, int SourceRowNumber, string? SourceSerialNumberRaw, string? RawCaseNumber, string? RawCaseTitle, string? RawCourt, string? RawStatus, string? SuggestedStatusClass, string? RawNdoh, DateOnly? ParsedNdoh, string? RawAdvocate, string? RawVillage, string? RawAwardNumber, string? LastOrderLinkState, string RowStatus, string ValidationIssuesJson);
public interface ICourtImportService { Task<CourtImportBatchDto> StageAsync(Stream source, string fileName, string? contentType, Guid userId, CancellationToken ct = default); Task<CourtImportBatchDto?> GetAsync(Guid id, CancellationToken ct = default); Task<IReadOnlyList<CourtImportBatchDto>> ListAsync(CancellationToken ct = default); Task<(IReadOnlyList<CourtImportRowDto> Items,int Total)> RowsAsync(Guid id,string? status,string? search,int? sourceRow,int page,int pageSize,CancellationToken ct=default); }

public sealed class CourtImportService(LacDbContext db, IDocumentStorage storage) : ICourtImportService
{
    public const string PrimarySheet = "Court case status pertains to L";
    private const long MaxBytes = 20 * 1024 * 1024;
    public async Task<CourtImportBatchDto> StageAsync(Stream source, string fileName, string? contentType, Guid userId, CancellationToken ct = default)
    {
        if (!string.Equals(Path.GetExtension(fileName), ".xlsx", StringComparison.OrdinalIgnoreCase)) throw new CourtWorkflowException("Only .xlsx workbooks are supported.", 400);
        if (source.CanSeek && source.Length > MaxBytes) throw new CourtWorkflowException("Workbook exceeds the 20 MB upload limit.", 400);
        var saved = await storage.SaveAndHashAsync(source, fileName, ct);
        if (saved.FileSize > MaxBytes) { await storage.DeleteAsync(saved.StoragePath, ct); throw new CourtWorkflowException("Workbook exceeds the 20 MB upload limit.", 400); }
        var actor = await db.AppUsers.AsNoTracking().Where(x=>x.Id==userId).Select(x=>x.DisplayName).FirstOrDefaultAsync(ct) ?? userId.ToString();
        var doc = new Document { DocumentType="Court Import Workbook", OriginalFileName=Path.GetFileName(fileName), StoragePath=saved.StoragePath, Sha256Hash=saved.Sha256Hash, MimeType=string.IsNullOrWhiteSpace(contentType)?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":contentType, FileSize=saved.FileSize, UploadedBy=actor };
        var batch = new CourtImportBatch { SourceDocument=doc, SourceSha256=saved.Sha256Hash, CreatedByUserId=userId, CreatedByDisplayNameSnapshot=actor };
        db.CourtImportBatches.Add(batch); await db.SaveChangesAsync(ct);
        try { await using var input=await storage.OpenReadAsync(saved.StoragePath,ct) ?? throw new InvalidDataException("Stored workbook could not be reopened."); Stage(batch,input); await db.SaveChangesAsync(ct); }
        catch(Exception ex) when(ex is not CourtWorkflowException) { batch.Status=CourtImportBatchStatus.Failed; batch.FailureMessage=ex.Message.Length>1000?ex.Message[..1000]:ex.Message; await db.SaveChangesAsync(ct); }
        return ToDto(batch);
    }
    private void Stage(CourtImportBatch batch, Stream input)
    {
        using var book=new XLWorkbook(input); var sheet=book.Worksheets.FirstOrDefault(x=>x.Name.Equals(PrimarySheet,StringComparison.Ordinal)); if(sheet is null) throw new InvalidDataException($"Required sheet '{PrimarySheet}' was not found.");
        var headerRow=sheet.Row(2); var map=HeaderMap(headerRow); foreach(var needed in new[]{"srno","ndoh","status","title","caseno","court"}) if(!map.ContainsKey(needed)) throw new InvalidDataException($"Required source column '{needed}' was not found.");
        var used=sheet.RangeUsed() ?? throw new InvalidDataException("Primary sheet is empty.");
        for(var rn=3;rn<=used.LastRow().RowNumber();rn++) { var row=sheet.Row(rn); if(row.Cells(1,used.LastColumn().ColumnNumber()).All(c=>c.IsEmpty())) continue; var cells=Enumerable.Range(1,used.LastColumn().ColumnNumber()).ToDictionary(i=>XLHelper.GetColumnLetterFromNumber(i),i=>CellText(row.Cell(i))); var staged=MakeRow(batch.Id,rn,cells,map); batch.Rows.Add(staged); }
        Classify(batch); batch.TotalRows=batch.Rows.Count; batch.ValidRows=batch.Rows.Count(x=>x.RowStatus is CourtImportRowStatus.NewCandidate or CourtImportRowStatus.ExistingExact); batch.NeedsReviewRows=batch.Rows.Count(x=>x.RowStatus is CourtImportRowStatus.NeedsReview or CourtImportRowStatus.PotentialDuplicate); batch.ConflictRows=batch.Rows.Count(x=>x.RowStatus==CourtImportRowStatus.IdentityConflict); batch.InvalidRows=batch.Rows.Count(x=>x.RowStatus==CourtImportRowStatus.Invalid); batch.Status=CourtImportBatchStatus.Parsed; batch.ParsedAt=DateTimeOffset.UtcNow;
    }
    private static Dictionary<string,int> HeaderMap(IXLRow header) { var result=new Dictionary<string,int>(); foreach(var c in header.CellsUsed()){var h=NormalizeHeader(CellText(c)); var k=h switch {"srno"=>"srno", "ndoh"=>"ndoh", "casestatus"=>"status", "recivedfromwhichadvocate"=>"advocate", "receivedfromwhichadvocate"=>"advocate", "casetitle"=>"title", "caseno"=>"caseno", "village"=>"village", "awardno"=>"award", "directions"=>"directions", "whichcourtpertainsto"=>"court", "lastorderlink"=>"link", "brieffactsofthecase"=>"facts", _=>""}; if(k!="")result[k]=c.Address.ColumnNumber;} return result; }
    private static CourtImportRow MakeRow(Guid batchId,int rn,Dictionary<string,string?> cells,Dictionary<string,int> m) { string? V(string k)=>m.TryGetValue(k,out var col)?cells[XLHelper.GetColumnLetterFromNumber(col)]:null; var rawNo=V("caseno"); var (type,num,year)=ParseCase(rawNo); var rawStatus=V("status"); var issues=new List<string>(); DateOnly? ndoh=ParseDate(V("ndoh")); if(!string.IsNullOrWhiteSpace(V("ndoh"))&&!ndoh.HasValue)issues.Add("NDOH is not a deterministic date."); if(string.IsNullOrWhiteSpace(rawStatus))issues.Add("Case status is blank."); var link=V("link"); var linkState=string.IsNullOrWhiteSpace(link)?"Missing":Uri.TryCreate(link,UriKind.Absolute,out var u)&&(u.Scheme==Uri.UriSchemeHttp||u.Scheme==Uri.UriSchemeHttps)?"ValidHttpUrl":"NeedsReview"; if(linkState=="NeedsReview")issues.Add("Last-order link is not an http/https URL."); var extras=cells.Where(x=>m.Values.All(v=>XLHelper.GetColumnLetterFromNumber(v)!=x.Key)&&!string.IsNullOrWhiteSpace(x.Value)).ToDictionary(x=>x.Key,x=>x.Value); var identity=type is null||num is null||year is null||string.IsNullOrWhiteSpace(V("court"))?null:$"{Key(V("court"))}|{type}|{num}|{year}"; return new CourtImportRow {BatchId=batchId,SourceRowNumber=rn,SourceSerialNumberRaw=V("srno"),RawRowJson=JsonSerializer.Serialize(cells),RawNdoh=V("ndoh"),ParsedNdoh=ndoh,RawStatus=rawStatus,SuggestedStatusClass=Status(rawStatus),RawAdvocate=V("advocate"),RawCaseTitle=V("title"),RawCaseNumber=rawNo,SuggestedCaseType=type,SuggestedCaseNumber=num,SuggestedCaseYear=year,RawVillage=V("village"),RawAwardNumber=V("award"),RawDirections=V("directions"),RawCourt=V("court"),SuggestedCourtName=Clean(V("court")),RawLastOrderLink=link,LastOrderLinkState=linkState,RawBriefFacts=V("facts"),ExtraCellsJson=JsonSerializer.Serialize(extras),IdentityKey=identity,RowStatus=identity is null||issues.Count>0?CourtImportRowStatus.NeedsReview:CourtImportRowStatus.NewCandidate,ValidationIssuesJson=JsonSerializer.Serialize(issues),SourceRowHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(cells)))).ToLowerInvariant()}; }
    private void Classify(CourtImportBatch batch) { foreach(var g in batch.Rows.Where(x=>x.IdentityKey!=null).GroupBy(x=>x.IdentityKey!)){if(g.Count()>1){var titles=g.Select(x=>Key(x.RawCaseTitle)).Distinct().ToList(); foreach(var r in g)r.RowStatus=titles.Count>1?CourtImportRowStatus.IdentityConflict:CourtImportRowStatus.PotentialDuplicate;}} foreach(var r in batch.Rows.Where(x=>x.IdentityKey!=null&&x.RowStatus==CourtImportRowStatus.NewCandidate)){var matches=db.CourtCases.AsNoTracking().Where(c=>c.RecordStatus==RecordStatus.Active).AsEnumerable().Where(c=>Key(c.CourtName)==Key(r.RawCourt)&&Key(c.CaseNumber)==Key(r.RawCaseNumber)).ToList(); if(matches.Count==1) r.RowStatus=Key(matches[0].CaseTitle)==Key(r.RawCaseTitle)?CourtImportRowStatus.ExistingExact:CourtImportRowStatus.IdentityConflict; if(matches.Count>0)r.CandidateCourtCaseId=matches[0].Id;}}
    private static (string?,string?,int?) ParseCase(string? s){if(string.IsNullOrWhiteSpace(s))return(null,null,null); var x=System.Text.RegularExpressions.Regex.Match(s.Trim(),@"^(?<t>[A-Za-z.() ]+)\s*(?:No\.?|[-/]?)\s*(?<n>\d+)\s*/\s*(?<y>\d{4})$"); return x.Success?(Clean(x.Groups["t"].Value),x.Groups["n"].Value,int.Parse(x.Groups["y"].Value,CultureInfo.InvariantCulture)):(null,null,null);}
    private static DateOnly? ParseDate(string? s)=>DateOnly.TryParseExact(s?.Trim(),new[]{"dd.MM.yyyy","d.M.yyyy","dd/MM/yyyy","d/M/yyyy","yyyy-MM-dd","M/d/yyyy"},CultureInfo.InvariantCulture,DateTimeStyles.None,out var d)?d:null;
    private static CourtImportStatusClass? Status(string? s)=>string.IsNullOrWhiteSpace(s)?null:Key(s) == "pending"?CourtImportStatusClass.Pending:Key(s).StartsWith("disposed")||Key(s)=="disposedoff"?CourtImportStatusClass.Disposed:CourtImportStatusClass.Attention;
    private static string? CellText(IXLCell c)=>c.IsEmpty()?null:c.GetFormattedString(); private static string NormalizeHeader(string? s)=>new string((s??"").Where(char.IsLetterOrDigit).ToArray()).ToLowerInvariant(); private static string Key(string? s)=>new string((s??"").Where(char.IsLetterOrDigit).ToArray()).ToLowerInvariant(); private static string? Clean(string? s)=>string.IsNullOrWhiteSpace(s)?null:string.Join(' ',s.Split((char[]?)null,StringSplitOptions.RemoveEmptyEntries));
    public async Task<CourtImportBatchDto?> GetAsync(Guid id,CancellationToken ct=default)=>await db.CourtImportBatches.AsNoTracking().Where(x=>x.Id==id).Select(x=>ToDto(x)).FirstOrDefaultAsync(ct);
    public async Task<IReadOnlyList<CourtImportBatchDto>> ListAsync(CancellationToken ct=default)=>await db.CourtImportBatches.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Select(x=>ToDto(x)).ToListAsync(ct);
    public async Task<(IReadOnlyList<CourtImportRowDto>,int)> RowsAsync(Guid id,string? status,string? search,int? sourceRow,int page,int pageSize,CancellationToken ct=default){var q=db.CourtImportRows.AsNoTracking().Where(x=>x.BatchId==id); if(Enum.TryParse<CourtImportRowStatus>(status,true,out var rs))q=q.Where(x=>x.RowStatus==rs);if(sourceRow.HasValue)q=q.Where(x=>x.SourceRowNumber==sourceRow);if(!string.IsNullOrWhiteSpace(search)){var s=search.ToLower();q=q.Where(x=>(x.RawCaseNumber??"").ToLower().Contains(s)||(x.RawCaseTitle??"").ToLower().Contains(s)||(x.RawCourt??"").ToLower().Contains(s));}var total=await q.CountAsync(ct);var items=await q.OrderBy(x=>x.SourceRowNumber).Skip((Math.Max(1,page)-1)*Math.Clamp(pageSize,1,100)).Take(Math.Clamp(pageSize,1,100)).Select(x=>new CourtImportRowDto(x.Id,x.SourceRowNumber,x.SourceSerialNumberRaw,x.RawCaseNumber,x.RawCaseTitle,x.RawCourt,x.RawStatus,x.SuggestedStatusClass==null?null:x.SuggestedStatusClass.ToString(),x.RawNdoh,x.ParsedNdoh,x.RawAdvocate,x.RawVillage,x.RawAwardNumber,x.LastOrderLinkState,x.RowStatus.ToString(),x.ValidationIssuesJson)).ToListAsync(ct);return(items,total);}
    private static CourtImportBatchDto ToDto(CourtImportBatch x)=>new(x.Id,x.Status.ToString(),x.SourceSheetName,x.TotalRows,x.ValidRows,x.NeedsReviewRows,x.ConflictRows,x.InvalidRows,x.FailureMessage,x.CreatedAt);
}
