using LAC.Domain;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
namespace LAC.Infrastructure;
public sealed class LacDbContext(DbContextOptions<LacDbContext> options) : DbContext(options) {
 public DbSet<AwardIngestionSession> AwardIngestionSessions => Set<AwardIngestionSession>(); public DbSet<AwardIngestionCandidate> AwardIngestionCandidates => Set<AwardIngestionCandidate>(); public DbSet<AwardDocumentExtractionJob> AwardDocumentExtractionJobs => Set<AwardDocumentExtractionJob>(); public DbSet<AwardDocumentPageExtraction> AwardDocumentPageExtractions => Set<AwardDocumentPageExtraction>();
 public DbSet<District> Districts => Set<District>(); public DbSet<SubDivision> SubDivisions => Set<SubDivision>(); public DbSet<Village> Villages => Set<Village>(); public DbSet<Khasra> Khasras => Set<Khasra>(); public DbSet<AcquisitionProject> AcquisitionProjects => Set<AcquisitionProject>(); public DbSet<Notification> Notifications => Set<Notification>(); public DbSet<Award> Awards => Set<Award>(); public DbSet<AwardVillage> AwardVillages => Set<AwardVillage>(); public DbSet<AwardNotification> AwardNotifications => Set<AwardNotification>(); public DbSet<KhasraReviewFlag> KhasraReviewFlags => Set<KhasraReviewFlag>(); public DbSet<PossessionEvent> PossessionEvents => Set<PossessionEvent>(); public DbSet<CourtCase> CourtCases => Set<CourtCase>(); public DbSet<Claim> Claims => Set<Claim>(); public DbSet<VillageLR> VillageLRs => Set<VillageLR>(); public DbSet<LREntry> LREntries => Set<LREntry>(); public DbSet<Party> Parties => Set<Party>(); public DbSet<KhatauniRecord> KhatauniRecords => Set<KhatauniRecord>(); public DbSet<Khata> Khatas => Set<Khata>(); public DbSet<KhataKhasra> KhataKhasras => Set<KhataKhasra>(); public DbSet<KhataPartyShare> KhataPartyShares => Set<KhataPartyShare>(); public DbSet<Document> Documents => Set<Document>(); public DbSet<DocumentVillage> DocumentVillages => Set<DocumentVillage>(); public DbSet<DocumentKhasra> DocumentKhasras => Set<DocumentKhasra>(); public DbSet<DocumentAward> DocumentAwards => Set<DocumentAward>(); public DbSet<DocumentNotification> DocumentNotifications => Set<DocumentNotification>(); public DbSet<DocumentVillageLR> DocumentVillageLRs => Set<DocumentVillageLR>(); public DbSet<DocumentKhatauniRecord> DocumentKhatauniRecords => Set<DocumentKhatauniRecord>(); public DbSet<AuditLog> AuditLogs => Set<AuditLog>();
 protected override void OnModelCreating(ModelBuilder b) { base.OnModelCreating(b); foreach(var e in b.Model.GetEntityTypes().Where(x=>typeof(OfficialRecord).IsAssignableFrom(x.ClrType))) b.Entity(e.ClrType).Property("RecordStatus").HasConversion<string>();
  b.Entity<AwardIngestionSession>().Property(x=>x.SourceType).HasConversion<string>(); b.Entity<AwardIngestionSession>().Property(x=>x.Status).HasConversion<string>(); b.Entity<AwardIngestionCandidate>().Property(x=>x.CandidateType).HasConversion<string>(); b.Entity<AwardIngestionCandidate>().Property(x=>x.Status).HasConversion<string>(); b.Entity<AwardIngestionCandidate>().Property(x=>x.Confidence).HasPrecision(5,4); b.Entity<AwardIngestionSession>().HasIndex(x=>x.CreatedAt); b.Entity<AwardIngestionCandidate>().HasIndex(x=>new{x.SessionId,x.Status}); b.Entity<AwardIngestionCandidate>().HasIndex(x=>new{x.SessionId,x.CandidateType}); b.Entity<AwardIngestionCandidate>().HasIndex(x=>x.CanonicalEntityId); b.Entity<AwardDocumentExtractionJob>().Property(x=>x.Status).HasConversion<string>(); b.Entity<AwardDocumentPageExtraction>().Property(x=>x.ExtractionMethod).HasConversion<string>(); b.Entity<AwardDocumentPageExtraction>().Property(x=>x.OcrConfidence).HasPrecision(5,4); b.Entity<AwardDocumentPageExtraction>().Property(x=>x.Width).HasPrecision(12,3); b.Entity<AwardDocumentPageExtraction>().Property(x=>x.Height).HasPrecision(12,3); b.Entity<AwardDocumentExtractionJob>().HasIndex(x=>new{x.Status,x.CreatedAt}); b.Entity<AwardDocumentExtractionJob>().HasIndex(x=>x.DocumentId); b.Entity<AwardDocumentPageExtraction>().HasIndex(x=>new{x.JobId,x.PageNumber}).IsUnique();
  b.Entity<District>().HasIndex(x=>x.Name).IsUnique(); b.Entity<SubDivision>().HasIndex(x=>new{x.DistrictId,x.Name}).IsUnique(); b.Entity<Village>().HasIndex(x=>new{x.SubDivisionId,x.Name}).IsUnique(); b.Entity<Khasra>().HasIndex(x=>new{x.VillageId,x.NormalizedNumber,x.Qualifier}); b.Entity<Khasra>().Property(x=>x.TotalArea).HasPrecision(18,4); b.Entity<Khasra>().Property(x=>x.AreaBigha).HasPrecision(18,4);
  b.Entity<Notification>().HasIndex(x=>new{x.SectionType,x.NotificationNumber,x.NotificationDate}).IsUnique(); b.Entity<Award>().HasIndex(x=>x.AwardNumber); b.Entity<NotificationKhasra>().HasIndex(x=>new{x.NotificationId,x.KhasraId}).IsUnique(); b.Entity<AwardKhasra>().HasIndex(x=>new{x.AwardId,x.KhasraId}).IsUnique(); b.Entity<AwardVillage>().HasIndex(x=>new{x.AwardId,x.VillageId}).IsUnique(); b.Entity<AwardNotification>().HasIndex(x=>new{x.AwardId,x.NotificationId}).IsUnique(); b.Entity<PossessionKhasra>().HasIndex(x=>new{x.PossessionEventId,x.KhasraId}).IsUnique(); b.Entity<CourtCaseAward>().HasIndex(x=>new{x.CourtCaseId,x.AwardId}).IsUnique(); b.Entity<CourtCaseKhasra>().HasIndex(x=>new{x.CourtCaseId,x.KhasraId}).IsUnique(); b.Entity<AwardKhasraClassification>().HasIndex(x=>new{x.AwardLandClassId,x.KhasraId}).IsUnique(); b.Entity<ClaimKhasra>().HasIndex(x=>new{x.ClaimId,x.KhasraId}).IsUnique(); b.Entity<AwardLandClass>().HasIndex(x=>new{x.AwardId,x.Code}).IsUnique(); b.Entity<VillageLR>().HasIndex(x=>x.VillageId); b.Entity<LREntry>().HasIndex(x=>x.VillageLRId); b.Entity<LREntry>().Property(x=>x.Revision).IsConcurrencyToken().HasDefaultValue(0); b.Entity<LREntry>().HasOne(x=>x.Section4Notification).WithMany().HasForeignKey(x=>x.Section4NotificationId); b.Entity<LREntry>().HasOne(x=>x.Section6Notification).WithMany().HasForeignKey(x=>x.Section6NotificationId); b.Entity<LREntry>().HasOne(x=>x.Award).WithMany().HasForeignKey(x=>x.AwardId);
  b.Entity<DocumentVillage>().HasIndex(x=>new{x.DocumentId,x.VillageId}).IsUnique(); b.Entity<DocumentKhasra>().HasIndex(x=>new{x.DocumentId,x.KhasraId}).IsUnique(); b.Entity<DocumentAward>().HasIndex(x=>new{x.DocumentId,x.AwardId}).IsUnique(); b.Entity<DocumentNotification>().HasIndex(x=>new{x.DocumentId,x.NotificationId}).IsUnique(); b.Entity<DocumentVillageLR>().HasIndex(x=>new{x.DocumentId,x.VillageLRId}).IsUnique();
  b.Entity<KhatauniRecord>().HasIndex(x=>x.VillageId); b.Entity<KhatauniRecord>().Property(x=>x.VerificationStatus).HasConversion<string>(); b.Entity<KhatauniRecord>().Property(x=>x.Version).IsConcurrencyToken().HasDefaultValue(0); b.Entity<KhatauniRecord>().HasOne(x=>x.SourceDocument).WithMany().HasForeignKey(x=>x.SourceDocumentId);
  b.Entity<Khata>().HasIndex(x=>new{x.KhatauniRecordId,x.KhataNumber}).IsUnique(); b.Entity<KhataKhasra>().HasIndex(x=>new{x.KhataId,x.KhasraId}).IsUnique(); b.Entity<KhataKhasra>().Property(x=>x.RecordedArea).HasPrecision(18,4); b.Entity<KhataPartyShare>().HasIndex(x=>new{x.KhataId,x.PartyId}).IsUnique(); b.Entity<KhataPartyShare>().Property(x=>x.VerificationStatus).HasConversion<string>(); b.Entity<KhataPartyShare>().Property(x=>x.Version).IsConcurrencyToken().HasDefaultValue(0); b.Entity<Party>().Property(x=>x.PartyType).HasConversion<string>(); b.Entity<Party>().Property(x=>x.Version).IsConcurrencyToken().HasDefaultValue(0); b.Entity<DocumentKhatauniRecord>().HasIndex(x=>new{x.DocumentId,x.KhatauniRecordId}).IsUnique();
  b.Entity<NotificationKhasra>().Property(x=>x.NotifiedArea).HasPrecision(18,4); b.Entity<AwardKhasra>().Property(x=>x.AcquiredArea).HasPrecision(18,4); b.Entity<AwardKhasra>().Property(x=>x.RecordedTotalAreaBigha).HasPrecision(18,4); b.Entity<AwardKhasra>().Property(x=>x.AwardedAreaBigha).HasPrecision(18,4); foreach(var property in new[]{nameof(AwardAreaSummary.AreaBigha),nameof(AwardAreaIssue.NotificationAreaBigha),nameof(AwardAreaIssue.FieldBookAreaBigha),nameof(AwardAreaIssue.DifferenceBigha),nameof(PossessionKhasra.AreaBigha),nameof(AwardKhasraClassification.AreaBigha),nameof(ClaimKhasra.ClaimedAreaBigha)}) { } b.Entity<AwardAreaSummary>().Property(x=>x.AreaBigha).HasPrecision(18,4); b.Entity<AwardAreaIssue>().Property(x=>x.NotificationAreaBigha).HasPrecision(18,4); b.Entity<AwardAreaIssue>().Property(x=>x.FieldBookAreaBigha).HasPrecision(18,4); b.Entity<AwardAreaIssue>().Property(x=>x.DifferenceBigha).HasPrecision(18,4); b.Entity<PossessionKhasra>().Property(x=>x.AreaBigha).HasPrecision(18,4); b.Entity<AwardKhasraClassification>().Property(x=>x.AreaBigha).HasPrecision(18,4); b.Entity<ClaimKhasra>().Property(x=>x.ClaimedAreaBigha).HasPrecision(18,4); b.Entity<AwardValuationRule>().Property(x=>x.RateAmount).HasPrecision(18,4); b.Entity<AwardCompensationRule>().Property(x=>x.RateAmount).HasPrecision(18,4); b.Entity<AwardCompensationRule>().Property(x=>x.RatePercent).HasPrecision(9,4); b.Entity<Claim>().Property(x=>x.ClaimedAmount).HasPrecision(18,4); b.Entity<Claim>().Property(x=>x.ClaimedRateAmount).HasPrecision(18,4); b.Entity<AwardApportionmentEntry>().Property(x=>x.Amount).HasPrecision(18,4); b.Entity<LREntry>().Property(x=>x.ParsedArea).HasPrecision(18,4); b.Entity<LREntry>().Property(x=>x.VerificationStatus).HasConversion<string>();
  foreach(var foreignKey in b.Model.GetEntityTypes().SelectMany(entity=>entity.GetForeignKeys())) foreignKey.DeleteBehavior=DeleteBehavior.Restrict;
 }
 public override async Task<int> SaveChangesAsync(CancellationToken ct=default) { var additions=ChangeTracker.Entries<Khasra>().Where(e=>e.State==EntityState.Added).Select(e=>e.Entity).ToList(); foreach(var khasra in additions) { var duplicateInRequest=additions.Any(x=>x!=khasra&&x.VillageId==khasra.VillageId&&x.NormalizedNumber==khasra.NormalizedNumber&&x.Qualifier==khasra.Qualifier); var duplicateInStore=await Khasras.AnyAsync(x=>x.VillageId==khasra.VillageId&&x.NormalizedNumber==khasra.NormalizedNumber&&x.Qualifier==khasra.Qualifier,ct); if(duplicateInRequest||duplicateInStore) throw new DbUpdateException("A Khasra with this normalized number and qualifier already exists in the village."); }
  var now=DateTimeOffset.UtcNow; var changes=ChangeTracker.Entries().Where(e=>e.Entity is OfficialRecord&&e.State is EntityState.Added or EntityState.Modified or EntityState.Deleted).ToList(); foreach(var entry in changes.Where(e=>e.State==EntityState.Deleted&&e.Entity is OfficialRecord)) { ((OfficialRecord)entry.Entity).RecordStatus=RecordStatus.Archived; entry.State=EntityState.Modified; } foreach(var e in ChangeTracker.Entries<OfficialRecord>()) { if(e.State==EntityState.Added) e.Entity.CreatedAt=now; if(e.State is EntityState.Added or EntityState.Modified) e.Entity.UpdatedAt=now; }
  foreach(var entry in changes) { var fields=entry.Properties.Where(p=>!p.Metadata.IsPrimaryKey()).ToDictionary(p=>p.Metadata.Name,p=>p.CurrentValue); AuditLogs.Add(new AuditLog { EntityType=entry.Metadata.ClrType.Name, EntityId=(Guid?)entry.Properties.FirstOrDefault(p=>p.Metadata.IsPrimaryKey())?.CurrentValue??Guid.Empty, Action=entry.State==EntityState.Added?"Created":entry.State==EntityState.Deleted?"Deleted":entry.Entity is OfficialRecord o&&o.RecordStatus==RecordStatus.Archived?"Archived":"Updated", ChangedAt=now, OldValues=entry.State==EntityState.Added?null:JsonSerializer.Serialize(entry.Properties.Where(p=>!p.Metadata.IsPrimaryKey()).ToDictionary(p=>p.Metadata.Name,p=>p.OriginalValue)), NewValues=entry.State==EntityState.Deleted?null:JsonSerializer.Serialize(fields) }); }
  return await base.SaveChangesAsync(ct); }
}
