using System.Diagnostics;
using System.Text.Json;
using Microsoft.Extensions.Options;
namespace LAC.Infrastructure;
public sealed class DocumentIntelligenceOptions { public bool Enabled {get;set;} public string? PythonExecutable {get;set;} public string? WorkerScript {get;set;} public string? WorkingDirectory {get;set;} public string? ModelCachePath {get;set;} public int TimeoutMinutes {get;set;}=15; }
public sealed record LocalDocumentIntelligenceInput(int ContractVersion,Guid DocumentId,string FilePath,Guid TargetAwardId,Guid? SelectedVillageId);
public sealed record LocalDocumentIntelligenceCandidate(string CandidateType,JsonElement StructuredPayload,int Page,JsonElement? SourceRegion,string? RawSourceText,string? RawOcr,string? NormalizedSuggestion,string? NormalizationReason,decimal? Confidence,IReadOnlyList<string>? InterpretationWarnings);
public sealed record LocalDocumentIntelligenceResult(int ContractVersion,Guid DocumentId,string Status,int PagesProcessed,IReadOnlyList<LocalDocumentIntelligenceCandidate> Candidates,IReadOnlyList<string> Warnings,JsonElement Metrics);
public interface ILocalDocumentIntelligenceClient { Task<LocalDocumentIntelligenceResult> RunAsync(LocalDocumentIntelligenceInput input,CancellationToken ct); }
public sealed class LocalDocumentIntelligenceClient(IOptions<DocumentIntelligenceOptions> configured) : ILocalDocumentIntelligenceClient {
 public async Task<LocalDocumentIntelligenceResult> RunAsync(LocalDocumentIntelligenceInput input,CancellationToken ct) {
  var o=configured.Value; if(!o.Enabled||string.IsNullOrWhiteSpace(o.PythonExecutable)||string.IsNullOrWhiteSpace(o.WorkerScript)) throw new InvalidOperationException("Local document intelligence is disabled or not configured.");
  var dir=Path.Combine(Path.GetTempPath(),"lac-document-intelligence",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var i=Path.Combine(dir,"input.json");var output=Path.Combine(dir,"output.json");
  try { await File.WriteAllTextAsync(i,JsonSerializer.Serialize(new {contractVersion=1,documentId=input.DocumentId,filePath=input.FilePath,targetAwardId=input.TargetAwardId,selectedVillageId=input.SelectedVillageId,options=new {processTables=true}}),ct); var psi=new ProcessStartInfo(o.PythonExecutable){UseShellExecute=false,RedirectStandardError=true,RedirectStandardOutput=true,CreateNoWindow=true};psi.ArgumentList.Add(o.WorkerScript);psi.ArgumentList.Add("--input");psi.ArgumentList.Add(i);psi.ArgumentList.Add("--output");psi.ArgumentList.Add(output);using var p=Process.Start(psi)??throw new InvalidOperationException("Local worker could not start.");using var timeout=CancellationTokenSource.CreateLinkedTokenSource(ct);timeout.CancelAfter(TimeSpan.FromMinutes(Math.Clamp(o.TimeoutMinutes,1,60)));await p.WaitForExitAsync(timeout.Token);if(p.ExitCode!=0)throw new InvalidOperationException("Local worker failed.");if(!File.Exists(output))throw new InvalidOperationException("Local worker returned no result.");var value=JsonSerializer.Deserialize<LocalDocumentIntelligenceResult>(await File.ReadAllTextAsync(output,timeout.Token))??throw new InvalidOperationException("Local worker result is malformed.");if(value.ContractVersion!=1||value.DocumentId!=input.DocumentId)throw new InvalidOperationException("Local worker contract validation failed.");return value; } finally { try{Directory.Delete(dir,true);}catch{} }
 }
}
