namespace LAC.Domain;

public enum RecordStatus { Active, Inactive, Archived }
public enum VerificationStatus { Draft, NeedsReview, Verified, Committed }
public enum RevenueRecordVerificationStatus { Draft, NeedsReview, Verified, Superseded }
public enum PartyType { Individual, GovernmentAgency, Institution, Other }
public abstract class OfficialRecord { public Guid Id { get; set; } = Guid.NewGuid(); public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; public string? CreatedBy { get; set; } public string? UpdatedBy { get; set; } public RecordStatus RecordStatus { get; set; } = RecordStatus.Active; }
public sealed class District : OfficialRecord { public string Name { get; set; } = ""; public ICollection<SubDivision> SubDivisions { get; set; } = new List<SubDivision>(); }
public sealed class SubDivision : OfficialRecord { public Guid DistrictId { get; set; } public District District { get; set; } = null!; public string Name { get; set; } = ""; public ICollection<Village> Villages { get; set; } = new List<Village>(); }
public sealed class Village : OfficialRecord { public Guid SubDivisionId { get; set; } public SubDivision SubDivision { get; set; } = null!; public string Name { get; set; } = ""; public ICollection<Khasra> Khasras { get; set; } = new List<Khasra>(); public ICollection<KhatauniRecord> KhatauniRecords { get; set; } = new List<KhatauniRecord>(); public ICollection<DocumentVillage> DocumentRelationships { get; set; } = new List<DocumentVillage>(); }
public sealed class Khasra : OfficialRecord { public Guid VillageId { get; set; } public Village Village { get; set; } = null!; public string DisplayNumber { get; set; } = ""; public string NormalizedNumber { get; set; } = ""; public string? Qualifier { get; set; } public string? RectangleNumber { get; set; } public string? KillaNumber { get; set; } public string? SubdivisionNumber { get; set; } public decimal? TotalArea { get; set; } public string? AreaUnit { get; set; } public decimal? AreaBigha { get; set; } public int? AreaBiswa { get; set; } public int? AreaBiswansi { get; set; } public string? Remarks { get; set; } public ICollection<AwardKhasra> AwardLinks { get; set; } = new List<AwardKhasra>(); public ICollection<NotificationKhasra> NotificationLinks { get; set; } = new List<NotificationKhasra>(); public ICollection<KhataKhasra> KhataLinks { get; set; } = new List<KhataKhasra>(); public ICollection<DocumentKhasra> DocumentRelationships { get; set; } = new List<DocumentKhasra>(); }
public sealed class AcquisitionProject : OfficialRecord { public string Name { get; set; } = ""; public string? RequiringAgency { get; set; } public string? ActRegime { get; set; } public string? Description { get; set; } }
public sealed class Notification : OfficialRecord { public Guid? AcquisitionProjectId { get; set; } public AcquisitionProject? AcquisitionProject { get; set; } public string SectionType { get; set; } = ""; public string NotificationNumber { get; set; } = ""; public DateOnly? NotificationDate { get; set; } public string? GazetteDetails { get; set; } public string? Remarks { get; set; } public ICollection<NotificationKhasra> KhasraLinks { get; set; } = new List<NotificationKhasra>(); public ICollection<DocumentNotification> DocumentRelationships { get; set; } = new List<DocumentNotification>(); }
public sealed class NotificationKhasra { public Guid Id { get; set; } = Guid.NewGuid(); public Guid NotificationId { get; set; } public Notification Notification { get; set; } = null!; public Guid KhasraId { get; set; } public Khasra Khasra { get; set; } = null!; public decimal? NotifiedArea { get; set; } public string? AreaUnit { get; set; } public string? Remarks { get; set; } }
public sealed class Award : OfficialRecord { public Guid? AcquisitionProjectId { get; set; } public AcquisitionProject? AcquisitionProject { get; set; } public string AwardNumber { get; set; } = ""; public DateOnly? AwardDate { get; set; } public string? AwardType { get; set; } public string? ActRegime { get; set; } public string Status { get; set; } = "Draft"; public string? Remarks { get; set; } public ICollection<AwardKhasra> KhasraLinks { get; set; } = new List<AwardKhasra>(); public ICollection<DocumentAward> DocumentRelationships { get; set; } = new List<DocumentAward>(); }
public sealed class AwardKhasra { public Guid Id { get; set; } = Guid.NewGuid(); public Guid AwardId { get; set; } public Award Award { get; set; } = null!; public Guid KhasraId { get; set; } public Khasra Khasra { get; set; } = null!; public decimal? AcquiredArea { get; set; } public string? AreaUnit { get; set; } public string? AcquisitionStatus { get; set; } public string? Remarks { get; set; } public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow; public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow; }
public sealed class VillageLR : OfficialRecord { public Guid VillageId { get; set; } public Village Village { get; set; } = null!; public string? RegisterReference { get; set; } public string? Remarks { get; set; } public ICollection<LREntry> Entries { get; set; } = new List<LREntry>(); public ICollection<DocumentVillageLR> DocumentRelationships { get; set; } = new List<DocumentVillageLR>(); }
public sealed class LREntry : OfficialRecord { public Guid VillageLRId { get; set; } public VillageLR VillageLR { get; set; } = null!; public int? RowNumber { get; set; } public string RawKhasraText { get; set; } = ""; public Guid? KhasraId { get; set; } public Khasra? Khasra { get; set; } public string? RawAreaText { get; set; } public decimal? ParsedArea { get; set; } public string? AreaUnit { get; set; } public Guid? Section4NotificationId { get; set; } public Notification? Section4Notification { get; set; } public Guid? Section6NotificationId { get; set; } public Notification? Section6Notification { get; set; } public Guid? AwardId { get; set; } public Award? Award { get; set; } public string? RawRemarks { get; set; } public VerificationStatus VerificationStatus { get; set; } = VerificationStatus.Draft; public int Revision { get; set; } }
public sealed class Party : OfficialRecord { public PartyType PartyType { get; set; } = PartyType.Individual; public string DisplayName { get; set; } = ""; public string? FatherOrSpouseName { get; set; } public string? AddressText { get; set; } public string? Remarks { get; set; } public int Version { get; set; } public ICollection<KhataPartyShare> KhataShares { get; set; } = new List<KhataPartyShare>(); }
public sealed class KhatauniRecord : OfficialRecord { public Guid VillageId { get; set; } public Village Village { get; set; } = null!; public string? ReferenceNumber { get; set; } public string? RecordYearText { get; set; } public DateOnly? AsOfDate { get; set; } public DateOnly? EffectiveFrom { get; set; } public DateOnly? EffectiveTo { get; set; } public string? Remarks { get; set; } public RevenueRecordVerificationStatus VerificationStatus { get; set; } = RevenueRecordVerificationStatus.Draft; public Guid? SourceDocumentId { get; set; } public Document? SourceDocument { get; set; } public int Version { get; set; } public ICollection<Khata> Khatas { get; set; } = new List<Khata>(); public ICollection<DocumentKhatauniRecord> DocumentRelationships { get; set; } = new List<DocumentKhatauniRecord>(); }
public sealed class Khata : OfficialRecord { public Guid KhatauniRecordId { get; set; } public KhatauniRecord KhatauniRecord { get; set; } = null!; public string KhataNumber { get; set; } = ""; public string? RawKhataNumber { get; set; } public string? Remarks { get; set; } public ICollection<KhataKhasra> KhasraLinks { get; set; } = new List<KhataKhasra>(); public ICollection<KhataPartyShare> PartyShares { get; set; } = new List<KhataPartyShare>(); }
public sealed class KhataKhasra : OfficialRecord { public Guid KhataId { get; set; } public Khata Khata { get; set; } = null!; public Guid KhasraId { get; set; } public Khasra Khasra { get; set; } = null!; public string? RawKhasraText { get; set; } public decimal? RecordedArea { get; set; } public string? RawAreaText { get; set; } public string? AreaUnit { get; set; } public string? Remarks { get; set; } }
public sealed class KhataPartyShare : OfficialRecord { public Guid KhataId { get; set; } public Khata Khata { get; set; } = null!; public Guid PartyId { get; set; } public Party Party { get; set; } = null!; public string? RawShareText { get; set; } public int? ShareNumerator { get; set; } public int? ShareDenominator { get; set; } public string? Remarks { get; set; } public RevenueRecordVerificationStatus VerificationStatus { get; set; } = RevenueRecordVerificationStatus.Draft; public int Version { get; set; } }
public sealed class Document : OfficialRecord { public string DocumentType { get; set; } = "Other"; public string OriginalFileName { get; set; } = ""; public string StoragePath { get; set; } = ""; public string? Sha256Hash { get; set; } public string? MimeType { get; set; } public long? FileSize { get; set; } public int Version { get; set; } = 1; public string Status { get; set; } = "Active"; public DateTimeOffset UploadedAt { get; set; } = DateTimeOffset.UtcNow; public string? UploadedBy { get; set; } public string? Remarks { get; set; } public ICollection<DocumentVillage> VillageLinks { get; set; } = new List<DocumentVillage>(); public ICollection<DocumentKhasra> KhasraLinks { get; set; } = new List<DocumentKhasra>(); public ICollection<DocumentAward> AwardLinks { get; set; } = new List<DocumentAward>(); public ICollection<DocumentNotification> NotificationLinks { get; set; } = new List<DocumentNotification>(); public ICollection<DocumentVillageLR> VillageLRLinks { get; set; } = new List<DocumentVillageLR>(); public ICollection<DocumentKhatauniRecord> KhatauniRecordLinks { get; set; } = new List<DocumentKhatauniRecord>(); }
public sealed class DocumentVillage { public Guid Id { get; set; } = Guid.NewGuid(); public Guid DocumentId { get; set; } public Document Document { get; set; } = null!; public Guid VillageId { get; set; } public Village Village { get; set; } = null!; }
public sealed class DocumentKhasra { public Guid Id { get; set; } = Guid.NewGuid(); public Guid DocumentId { get; set; } public Document Document { get; set; } = null!; public Guid KhasraId { get; set; } public Khasra Khasra { get; set; } = null!; }
public sealed class DocumentAward { public Guid Id { get; set; } = Guid.NewGuid(); public Guid DocumentId { get; set; } public Document Document { get; set; } = null!; public Guid AwardId { get; set; } public Award Award { get; set; } = null!; }
public sealed class DocumentNotification { public Guid Id { get; set; } = Guid.NewGuid(); public Guid DocumentId { get; set; } public Document Document { get; set; } = null!; public Guid NotificationId { get; set; } public Notification Notification { get; set; } = null!; }
public sealed class DocumentVillageLR { public Guid Id { get; set; } = Guid.NewGuid(); public Guid DocumentId { get; set; } public Document Document { get; set; } = null!; public Guid VillageLRId { get; set; } public VillageLR VillageLR { get; set; } = null!; }
public sealed class DocumentKhatauniRecord { public Guid Id { get; set; } = Guid.NewGuid(); public Guid DocumentId { get; set; } public Document Document { get; set; } = null!; public Guid KhatauniRecordId { get; set; } public KhatauniRecord KhatauniRecord { get; set; } = null!; }
public sealed class AuditLog { public Guid Id { get; set; } = Guid.NewGuid(); public string EntityType { get; set; } = ""; public Guid EntityId { get; set; } public string Action { get; set; } = ""; public DateTimeOffset ChangedAt { get; set; } = DateTimeOffset.UtcNow; public string? ChangedBy { get; set; } public string? OldValues { get; set; } public string? NewValues { get; set; } }
