"""V2 source-reviewed foundation. No model output is imported as a target.

Tuple: page, exact native passage, category, field, scope, actor, review reason.
Only fully read sources are listed. Other acquired sources remain UNREVIEWED.
This is not the final V2 dataset or permission to launch GPU training.
"""
REVIEWED = {
 'wpc9093-2022-apr2024': ('2024-04-08', [
  (1, '1. Mr. Digvijay Rai, the learned counsel appearing for the petitioners submits that the subject land (admeasuring one bigha) located in Khasra No. 27//22 of Village – Bharthal, New Delhi was not acquired but it appears that the possession of the said land was taken over.', 'PETITIONER_SUBMISSION', 'possession', 'Current', 'Petitioner', 'Possession/acquisition claim is not a judicial finding.'),
  (1, 'He submits that the said land is required to be demarcated and the possession of the land is required to be handed over to the petitioners and he is also entitled to compensation for illegal use of the same.', 'PETITIONER_SUBMISSION', 'compensation', 'Current', 'Petitioner', 'Requested compensation and handover are not relief granted or proven compensation facts.'),
  (1, 'The issue relates to demarcation of the petitioners’ land.', 'CASE_CONTEXT', 'context', 'Current', 'Court', 'Court identifies the dispute, not a possession/compensation finding.'),
  (2, '3. List on 30.07.2024.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Old listing superseded in later chain; never a claim of an actual order on this date.')]),
 'wpc5084-2018-nov2020': ('2020-11-24', [
  (1, '1. The counsel for the petitioner in W.P.(C)5084/2018 states that petitioner No.4(i) Anoop Singh has died leaving Puneet S. Girsa and Rikesh Girsa only as his legal heirs.', 'PETITIONER_SUBMISSION', 'context', 'Current', 'Petitioner', 'Counsel statement retains attribution; substitution is separately recorded below.'),
  (2, '3. For the reasons stated, Puneet S. Girsa and Rikesh Girsa are substituted in place of Anoop Singh.', 'PROCEDURAL_EVENT', 'context', 'Current', 'Court', 'Operative substitution, not a land title finding.'),
  (2, '4. Counsel for the respondents LAC seeks adjournment.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'LAC', 'Adjournment request is not performance of an office action.'),
  (2, '5. List for hearing on 29th January, 2021.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Actual November order listing only.')]),
 'wpc5084-2018': ('2026-08-25', [
  (2, '2. Let the flowcharts filed by the Petitioner and Respondent Nos. 4 and 5 be exchanged with each other.', 'COURT_DIRECTION', 'direction', 'Current', 'Petitioner/Respondents 4 and 5', 'No actor proof that respondents 4/5 are LAC; do not infer a named LAC-only duty.'),
  (2, '3. Ld. Counsels to make their submissions on the next date of hearing.', 'COURT_DIRECTION', 'direction', 'Current', 'Counsel', 'General counsel duty, not a specific LAC filing obligation.'),
  (2, '4. List on 10th December, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Exact latest supplied listing.')]),
 'wpc9889-2024': ('2025-12-12', [
  (1, '1. We are informed that respondents shall remove the objections qua the counter submitted by them within a period of two weeks.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'Respondents', 'Reported intention to remove objections, not recorded completion.'),
  (1, '2. As such, we grant time, as prayed.', 'PROCEDURAL_EVENT', 'context', 'Current', 'Court', 'Time grant alone does not prove removal/compliance or explicit LAC assignment.'),
  (1, '3. List on 17th March 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Source-backed listing only.')]),
 'cont1094-2026': ('2026-07-03', [
  (1, '1. The present contempt petition has been filed alleging wilful and deliberate disobedience of the judgment dated 29th July, 2025, passed by this Court in W.P.(C) 10546/2023, titled as Rasesh Gupta & Anr. Versus Union of India & Ors.', 'CASE_CONTEXT', 'context', 'Current', 'Petitioner', 'Contempt alleges disobedience; allegation is not an adjudicated finding of wilful contempt.'),
  (2, '2. It is submitted that by way of the aforesaid judgment, this Court had directed the respondents to re-assess the compensation payable to the petitioners under the provisions of the Right to Fair Compensation and Transparency in Land Acquisition, Rehabilitation and Resettlement Act, 2013.', 'PETITIONER_SUBMISSION', 'compensation', 'Historical', 'Petitioner', 'Submitted description of earlier judgment is not a fresh reassessment direction in this notice order.'),
  (2, 'However, the respondents have failed to determine or re-assess the compensation payable to the petitioners till date.', 'PETITIONER_SUBMISSION', 'compensation', 'Current', 'Petitioner', 'Same submitted allegation continues; no Court finding of completed or failed reassessment is invented.'),
  (2, '4. Learned counsel appearing for the Land Acquisition Collector (“LAC”), submits that a review petition with regard to the aforesaid judgment has already been filed by the LAC.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'LAC', 'Claim of filing review is not stay of judgment, compliance, or review being allowed.'),
  (2, '5. Accordingly, let reply be filed by the respondents, within a period of four weeks, from today.', 'COURT_DIRECTION', 'filing', 'Current', 'Respondent', 'Generic respondents: do not turn into an explicit individual LAC-only obligation.'),
  (2, '7. List for consideration on 18th November, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Exact listing only.')]),
 'cont418-2025': ('2026-07-13', [
  (1, '1. The present contempt petition has been filed alleging non-compliance and disobedience of the order dated 17th May, 2019, passed in W.P.(C) 5437/2019, titled as Manpreet Singh Versus Government of State of NCT of Delhi through Gram Sabha, Rangpuri, Malikpur Kohi and Anr.', 'CASE_CONTEXT', 'context', 'Current', 'Petitioner', 'Contempt allegation is not an adjudicated wilful-disobedience finding.'),
  (2, '3. Perusal of the aforesaid order clearly shows that there were directions by this Court to take action for removal of encroachment and illegal construction from the land, i.e., Khasra No. 1049, Village Malikpur Kohi @ Rangpuri, Delhi.', 'COURT_OBSERVATION', 'observation', 'Historical', 'Court', 'Court describes earlier direction; image-only quoted original is not reconstructed or OCRed.'),
  (2, '4. This Court notes the submission made by learned counsel for the petitioner that no such action for removal of encroachment or unauthorized construction has taken place till date.', 'PETITIONER_SUBMISSION', 'context', 'Current', 'Petitioner', 'Court noting a submission does not establish the submitted allegation.'),
  (3, '6. Per contra, learned counsel for the DDA submits that even though the land in question may have been urbanized in the year 2020, however, the same has not been formally handed over to the DDA, as yet.', 'OTHER_PARTY_SUBMISSION', 'possession', 'Current', 'DDA', 'Disputed DDA stand, not a Court possession finding.'),
  (3, '8. The Chief Secretary shall ensure that the issue as regards the authority, under whose jurisdiction the aforesaid land is now situated, is resolved.', 'COURT_DIRECTION', 'direction', 'Current', 'Chief Secretary', 'Named other officer; no inferred LAC obligation.'),
  (3, '9. After the aforesaid dispute is resolved, the concerned authority shall take action for removal of encroachment and illegal construction in terms of the order dated 17th May, 2019, as aforesaid.', 'COURT_DIRECTION', 'direction', 'Current', 'Concerned authority', 'Preserve prerequisite jurisdiction resolution, not immediate unconditional removal by LAC.'),
  (3, '10. Let the meeting be called by the Chief Secretary, GNCTD, within a period of three weeks from today.', 'COURT_DIRECTION', 'direction', 'Current', 'Chief Secretary', 'Meeting duty belongs to Chief Secretary.'),
  (4, '14. List on 12th January, 2027.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Court listing is not a meeting date.')]),
 'wpc5645-2022': ('2026-05-07', [
  (1, '2. Ld. Counsel for the Petitioner wishes to file rejoinder to DDA’s counter affidavit.', 'PETITIONER_SUBMISSION', 'context', 'Current', 'Petitioner', 'Intention to file is not recorded filing.'),
  (1, 'Let the same be filed within six weeks.', 'COURT_DIRECTION', 'filing', 'Current', 'Petitioner', 'Same refers to petitioner rejoinder, not LAC counter affidavit.'),
  (1, '3. LAC has not filed a counter affidavit. Their right to file the same stands closed.', 'PROCEDURAL_EVENT', 'filing', 'Current', 'LAC', 'Express closure supersedes opportunity to file; not a fresh filing obligation or completed compliance.'),
  (1, '4. List on 21st September, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Listing only, not actual order on that future date.')]),
 'wpc6108-2015-nov2025': ('2025-11-11', [
  (39, '14. Counsel appearing for respondent/Land Acquisition Collector (‘LAC’) shall submit a “Master List” of all matters, as per the categorization ordered by the Hon’ble Apex Court.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Express master-list obligation; no assumption that it has been submitted.'),
  (39, 'Let this “Master List” be submitted before the Registrar, and a copy of which be placed with each of the matters.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Same master list and actor as immediately preceding sentence.'),
  (44, '16. Ms. Smita Maan, counsel appearing for petitioner and Ms Malvika Kapila appearing for respondent/ Delhi Development Authority (‘DDA’) undertake to prepare, with mutual consultation, a ‘Blank Template’ containing an optimum format to be used by parties/counsel subsequently to populate with material facts, which according to them are necessary for the purpose of consideration and deciding the issue.', 'OTHER_PARTY_SUBMISSION', 'context', 'Current', 'Petitioner/DDA', 'Joint counsel undertaking, not recorded completion or LAC template preparation duty.'),
  (45, '18. Re-notify before this Court on 25th February, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Historical order has its own current listing; later orders supersede this listing.')]),
 'wpc6108-2015-feb25': ('2026-02-25', [
  (36, '16. Ms. Smita Maan, counsel appearing for petitioner and Ms Malvika Kapila appearing for respondent/ Delhi Development Authority (‘DDA’) undertake to prepare, with mutual consultation, a ‘Blank Template’ containing an optimum format to be used by parties/counsel subsequently to populate with material facts, which according to them are necessary for the purpose of consideration and deciding the issue.', 'OTHER_PARTY_SUBMISSION', 'context', 'Quoted', 'Petitioner/DDA', 'Reproduced November undertaking, not a fresh LAC direction.'),
  (37, '4. Today, both the ld. Counsels have placed before the Court their respective ‘Blank Template’.', 'RECORDED_COMPLIANCE', 'compliance', 'Current', 'Petitioner/DDA', 'Court records the earlier blank-template undertaking fulfilled; not LAC populated-template completion.'),
  (37, '6. After considering the respective suggestions from the ld. Counsels appearing on behalf of the parties, the Court has finalised the ‘Blank Template’.', 'PROCEDURAL_EVENT', 'context', 'Current', 'Court', 'Court finalisation differs from parties filing populated templates.'),
  (37, '7. In each of these matters, the templates shall be duly filled up and filed by ld. Counsels for the Petitioners and ld. Counsels for the Land Acquisition Collector (hereinafter, ‘LAC’) and DDA separately.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Current express separate populated-template duty applies to LAC.'),
  (37, '(ii) Filing of duly filled up templates by ld. Counsels for the Petitioners, the LAC & DDA shall be completed by 30th April, 2026.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Deadline is an obligation, not a completion event.'),
  (44, '11. List all these matters before Court on 7th May, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Court listing is distinct from Registrar schedule in intervening pages.')]),
 'wpc13932-2025-sep2025': ('2025-09-10', [
  (1, 'He is seeking a declaration that he is entitled to own and enjoy the property, which he purchased under the Sale Deed dated 19th September 1994.', 'PETITIONER_SUBMISSION', 'context', 'Current', 'Petitioner', 'Relief sought is not a declaration granted.'),
  (2, '3. The fact remains that the land-in-question was subjected to acquisition through an Award passed under the Land Acquisition Act 1894 (“Act of 1894”) on 19th September 1986.', 'COURT_FINDING', 'award', 'Historical', 'Court', 'Recorded historical Award date; does not prove compensation payment or current title.'),
  (2, 'It is claimed that under aforesaid legal right, he is entitled to claim the land from the respondent/Authority, and at the very least the respondent/Authority should release the land from it’s possession.', 'PETITIONER_SUBMISSION', 'possession', 'Current', 'Petitioner', 'Release/entitlement claimed, not Court possession/title finding.'),
  (3, '9. Let reply be filed within a period of four weeks; rejoinder thereto, if any, be filed within two weeks thereafter, with copies to the opposing counsel.', 'COURT_DIRECTION', 'filing', 'Current', 'Respondent/Petitioner', 'Multiple procedural actors; generic respondent reply must not become an explicit LAC office duty.'),
  (3, '11. List on 17th October 2025.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Only this order listing, not latest chain date.')]),
 'wpc13932-2025-feb03': ('2026-02-03', [
  (1, '3. Vide order dated 10th September, 2025, the submission of ld. Sr. Counsel for the Petitioner had been recorded that the original owners of the property would be impleaded in this case.', 'PETITIONER_SUBMISSION', 'context', 'Historical', 'Petitioner', 'Recalled promise, not itself a present completed impleadment.'),
  (2, '7. Thus, all the original owners stood served in terms of the amended memo parties attached with application CM APPL. 61807/2025.', 'RECORDED_COMPLIANCE', 'compliance', 'Current', 'Petitioner', 'Court explicitly records service; do not equate service with every application being allowed.'),
  (3, '13. List before the Court on 20th April, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Court date distinct from Joint Registrar date of 2 March.')]),
 'wpc13932-2025': ('2026-08-21', [
  (1, 'CM APPL. 57009/2025 2. This is an application filed by the Petitioners seeking permission to file lengthy synopsis and list of dates. 3. For the reasons stated in the application, the same is allowed. 4. Application is disposed of.', 'PROCEDURAL_EVENT', 'disposition', 'Current', 'Court', 'Disposition is limited to named application, never the writ.'),
  (2, 'The original owners are, accordingly, impleaded in this matter.', 'PROCEDURAL_EVENT', 'context', 'Current', 'Court', 'Present judicial impleadment distinguishes earlier petitioner promise and service.'),
  (2, '7. The counter affidavits are stated to have been filed.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'Respondent', 'Stated filing is not unqualified Court-confirmed completed compliance.'),
  (2, 'Delay in filing the counter affidavits by all the Respondents, if any, is condoned.', 'PROCEDURAL_EVENT', 'context', 'Current', 'Court', 'Judicial procedural condonation, not a filing obligation; if-any qualification remains intact.'),
  (2, '9. The amended memo of parties has not come on record. Let the same be brought on record.', 'COURT_DIRECTION', 'filing', 'Current', 'Petitioner', 'Remaining memo action cannot be attributed to LAC.'),
  (2, '10. List for hearing on 14th December, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Latest supplied order listing; not proof of full order history.')]),
 'wpc4806-2014-feb2020': ('2020-02-04', [
  (1, 'Learned counsel for the respondents states that there are errors in the counter-affidavit, as filed, and she will file another counter-affidavit.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'Respondent', 'Counsel promise is not a completed replacement affidavit.'),
  (1, 'Let the same be filed within four weeks.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'LAC is named respondent in caption; same refers to the preceding corrected counter-affidavit.'),
  (1, 'Rejoinder thereto, if any, be filed before the next date.', 'COURT_DIRECTION', 'filing', 'Current', 'Petitioner', 'Rejoinder obligation is not a LAC duty.'),
  (1, 'List on 24.09.2020.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Source-confirmed listing in this historical order, not current calendar hearing.')]),
 'wpc4806-2014-apr2022': ('2022-04-11', [
  (1, '1. Learned counsel for the respondent/ LAC seeks further time to file the counter affidavit in terms of the errors in the earlier counter affidavit, as noted in the order dated 4th February, 2020.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'LAC', 'Request for time is not recorded compliance.'),
  (1, '2. Last opportunity is granted to the respondent/LAC to file a proper detailed affidavit within three weeks.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Passive grant expressly identifies respondent/LAC and required affidavit.'),
  (1, '3. List on 6th May, 2022.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Actual listing direction, not proof that an order exists on that future date.')]),
 'wpc4806-2014': ('2026-02-07', [
  (1, '3. An additional affidavit was to be filed by the Land Acquisition Collector (hereinafter, ‘LAC’) in this matter in terms of the order dated 4th February, 2020 as there were errors in the counter affidavit.', 'CASE_CONTEXT', 'context', 'Historical', 'LAC', 'Narrates earlier requirement; not a fresh direction or proof of filing.'),
  (1, '5. More than five years have passed and the errors have not been corrected till date.', 'COURT_OBSERVATION', 'observation', 'Current', 'Court', 'Court records non-correction, not presumed completion from elapsed time.'),
  (2, '10. In the meantime, the office of the LAC shall also file an additional affidavit within a period of four weeks as a last opportunity.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Express present LAC obligation renews the filing requirement.'),
  (2, 'If the same is not filed in four weeks, a cost of Rs. 10,000/- shall be deposited with the Delhi High Court Legal Services Committee, without which, the affidavit shall not be taken on record.', 'COURT_DIRECTION', 'direction', 'Current', 'LAC', 'Conditional consequence retained verbatim; not unconditional immediate costs.'),
  (2, '11. List on 20th April, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Latest available source-confirmed listing in the supplied chain only.')]),
 'wpc6108-2015': ('2026-03-20', [
  (1, 'Additional affidavit has only been filed by respondent no.3. Rejoinder thereto has also been filed.', 'DOCUMENT_OR_FILING_FACT', 'filing', 'Current', 'Respondent', 'Do not infer identity of respondent 3 or completion by all parties.'),
  (1, 'The compliance with regard to filing of duly filled up templates by counsels for the petitioner, the LAC and the DDA be completed by 30.04.2026 in view of order dated 25.02.2026 passed by the Hon’ble Court.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Passive renewed direction names LAC explicitly; compliance wording is an obligation, not completion.'),
  (1, 'The matter is already listed before the Hon’ble Court on 07.05.2026.', 'PROCEDURAL_EVENT', 'nextHearing', 'Current', 'Court', 'Confirms an existing listing, not an order dated 7 May.')]),
 'wpc4255-2016': ('2026-04-06', [
  (1, 'Additional affidavit has been filed by respondent no.3.', 'DOCUMENT_OR_FILING_FACT', 'filing', 'Current', 'Respondent', 'Identity of respondent 3 is not inferred as LAC from advocate list.'),
  (1, 'The compliance with regard to filing of duly filled up templates by counsels for the petitioner, the LAC and the DDA be completed by 30.04.2026 in view of order dated 25.02.2026 passed by the Hon’ble Court.', 'COURT_DIRECTION', 'filing', 'Current', 'LAC', 'Explicit LAC template obligation; completion remains unconfirmed.'),
  (1, 'The matter is already listed before the Hon’ble Court on 07.05.2026.', 'PROCEDURAL_EVENT', 'nextHearing', 'Current', 'Court', 'This common-source family must remain together with 6108.')]),
 'wpc9093-2022-feb09': ('2026-02-09', [
  (1, '3. In the said status report, it is stated that the land parcel falls within the premises of Yashobhoomi, which is an International Convention Centre located in Dwarka.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'Respondent', 'SDM status-report assertion is not a Court finding of acquisition or possession.'),
  (1, '4. In view thereof, the Petitioner prays for impleadment of the Ministry of Commerce (DPIIT) for completing the demarcation of the land parcel.', 'PETITIONER_SUBMISSION', 'context', 'Current', 'Petitioner', 'Petitioner prayer is separated from the following judicial impleadment.'),
  (1, '5. Accordingly, let the Ministry of Commerce (DPIIT) be impleaded as Respondent No. 4 in this case.', 'COURT_DIRECTION', 'direction', 'Current', 'Court', 'Fresh impleadment direction does not require an affidavit by LAC.'),
  (2, '6. Ms. Kalra, ld. CGSC, who is present in Court shall seek instructions and file an affidavit on behalf of the Ministry of Commerce (DPIIT).', 'COURT_DIRECTION', 'filing', 'Current', 'DPIIT', 'Named ministry obligation must not become a LAC duty.'),
  (2, '8. List on 24th April, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Do not fabricate an order for this listing date.')]),
 'wpc9093-2022': ('2026-08-24', [
  (1, '3. A status report has been filed on behalf of DPIIT and the same has been perused by the Court.', 'DOCUMENT_OR_FILING_FACT', 'filing', 'Current', 'DPIIT', 'Judicially recorded filing is by DPIIT, not compliance of all LAC obligations.'),
  (2, '7. In our view, all the authorities are speaking in different voices.', 'COURT_OBSERVATION', 'observation', 'Current', 'Court', 'Disagreement is recorded; acquisition and compensation remain issues to resolve.'),
  (3, '9. Let a joint meeting be held in this regard under the aegis of Secretary, DPIIT where the LAC and the DDA shall also be present, so that the issue can be resolved amongst the three authorities.', 'COURT_DIRECTION', 'direction', 'Current', 'LAC', 'LAC participation is expressly required; not an inferred generic respondent duty.'),
  (3, '10. The meeting shall take place on 14th September, 2026 at 3:00 PM in the office of Secretary, DPIIT.', 'COURT_DIRECTION', 'direction', 'Current', 'LAC', 'Meeting scheduling read with preceding mandatory LAC presence; date is not the hearing.'),
  (3, '12. The DDA and the LAC shall produce in the meeting their land records in support of their stand, including the handing over and taking over record.', 'COURT_DIRECTION', 'direction', 'Current', 'LAC', 'Explicit records obligation; no claim that handover actually occurred.'),
  (3, '13. The Secretary, DPIIT, after going through the records, and holding a meeting, shall place further status report before this Court on the next date of hearing.', 'COURT_DIRECTION', 'filing', 'Current', 'DPIIT', 'Status report is assigned to Secretary/DPIIT, not LAC.'),
  (4, '14. List on 11th December, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Different from 14 September meeting date.')]),
 'wpc14785-2023': ('2026-09-01', [
  (1, '2. The rejoinder to the counter affidavit of Respondent No. 4 is stated to have been returned under objections.', 'PETITIONER_SUBMISSION', 'context', 'Current', 'Petitioner', 'Reported filing problem retains stated-to qualification, not an unqualified Court-confirmed completion or LAC noncompliance.'),
  (1, '4. This is the last and final opportunity for the Petitioner to bring the rejoinder on record and argue the matter on the next date.', 'COURT_DIRECTION', 'filing', 'Current', 'Petitioner', 'Petitioner-specific action is a difficult LAC NONE example.'),
  (1, 'If there is no appearance on the next date on behalf of the Petitioner, the petition would be liable to be dismissed for non-prosecution.', 'COURT_OBSERVATION', 'observation', 'Current', 'Court', 'Conditional future dismissal is not actual present disposition.'),
  (1, '5. List on 17th December, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Exact source-backed listing.')]),
 'wpc4644-2024': ('2026-02-23', [
  (1, '2. Ld. Counsel for the Land Acquisition Collector submits that the counter affidavit has been filed yesterday.', 'LAC_OR_RESPONDENT_SUBMISSION', 'context', 'Current', 'LAC', 'Counsel filing statement must not itself become recorded completion.'),
  (1, 'Delay in filing the counter affidavit, if any, is condoned. Let the same be brought on record.', 'COURT_DIRECTION', 'filing', 'Current', 'Respondent', 'Acceptance/bring-on-record direction preserves if-any qualification; no invented completion.'),
  (1, '3. Let the rejoinder be filed within a period of six weeks.', 'COURT_DIRECTION', 'filing', 'Current', 'Petitioner', 'Rejoinder is not LAC obligation.'),
  (1, '4. List this matter for hearing on 18th May, 2026.', 'COURT_DIRECTION', 'nextHearing', 'Current', 'Court', 'Listing alone does not establish a later order.')]),
}

QUARANTINED = [
 {'id': 'wpc12994-2023-deadline', 'reason': 'January 2026 order twice says February 2025; do not silently repair deadline.'},
 {'id': 'wpc10105-2023-blind-gold', 'reason': 'Four official source versions acquired; reserved blind gold annotation and leakage audit remain pending. Never promote to training.'},
]
